-- Paso 13.4 · Administración cotidiana y puerta obligatoria de publicación.
--
-- Esta migración es posterior al mercado vivo. No sustituye ni vuelve a ejecutar
-- 20260801172543_add_live_prediction_market_model.sql.
-- Los borradores, informes y auditoría viven en el esquema privado y solo se
-- alcanzan mediante RPC con autorización administrativa revalidada en servidor.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

alter table public.markets
  add column if not exists evaluation_ends_at timestamptz,
  add column if not exists evaluation_timezone text,
  add column if not exists resolution_deadline timestamptz,
  add column if not exists participation_closed_at timestamptz,
  add column if not exists participation_close_reason text,
  add column if not exists market_definition_version bigint not null default 1;

comment on column public.markets.evaluation_ends_at is
  'Final original del periodo que debe investigarse al resolver. No se acorta con un cierre anticipado.';
comment on column public.markets.evaluation_timezone is
  'Zona IANA usada para interpretar el final original del periodo evaluado.';
comment on column public.markets.participation_closed_at is
  'Hora real de cierre anticipado de nuevas participaciones, sin alterar el periodo evaluado.';

create table if not exists private.market_drafts (
  id uuid primary key default gen_random_uuid(),
  market_id text unique,
  market_slug text not null,
  question text,
  subject text,
  category text,
  yes_option text not null default 'Sí',
  no_option text not null default 'No',
  evaluation_period_label text,
  evaluation_ends_at timestamptz,
  closes_at timestamptz,
  timezone text,
  resolution_deadline timestamptz,
  yes_criteria text,
  no_criteria text,
  edge_cases text,
  primary_source jsonb not null default '{}'::jsonb,
  alternative_sources jsonb not null default '[]'::jsonb,
  delay_treatment text,
  cancellation_treatment text,
  leak_treatment text,
  rename_treatment text,
  assumptions text,
  public_criteria text,
  description text,
  workflow_status text not null default 'draft_incomplete'
    check (workflow_status in (
      'draft_incomplete', 'draft_ready', 'review_pending', 'review_in_progress',
      'review_rejected', 'review_inconclusive', 'review_unavailable',
      'review_approved', 'human_confirmed', 'scheduled', 'published',
      'early_closed', 'cancelled', 'pending_resolution', 'resolved', 'annulled'
    )),
  content_version bigint not null default 1 check (content_version > 0),
  content_fingerprint text,
  reviewed_version bigint,
  reviewed_fingerprint text,
  review_status text not null default 'not_requested'
    check (review_status in (
      'not_requested', 'pending', 'in_progress', 'approved', 'rejected',
      'inconclusive', 'service_unavailable', 'quota_exhausted', 'invalid_response'
    )),
  human_confirmed_at timestamptz,
  human_confirmed_by uuid,
  scheduled_for timestamptz,
  published_at timestamptz,
  published_by uuid,
  created_by uuid not null,
  updated_by uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_drafts_slug_check
    check (market_slug ~ '^[a-z0-9][a-z0-9-]{2,119}$'),
  constraint market_drafts_sources_check
    check (jsonb_typeof(primary_source) = 'object' and jsonb_typeof(alternative_sources) = 'array'),
  constraint market_drafts_temporal_check
    check (
      (evaluation_ends_at is null and closes_at is null)
      or evaluation_ends_at = closes_at
    )
);

create table if not exists private.market_review_reports (
  id bigint generated by default as identity primary key,
  draft_id uuid not null references private.market_drafts(id) on delete cascade,
  draft_version bigint not null,
  content_fingerprint text not null,
  validator_version text not null,
  result text not null
    check (result in (
      'approved', 'rejected', 'inconclusive', 'service_unavailable',
      'quota_exhausted', 'invalid_response'
    )),
  deterministic_issues jsonb not null default '[]'::jsonb,
  semantic_issues jsonb not null default '[]'::jsonb,
  editorial_notes jsonb not null default '[]'::jsonb,
  reviewed_by uuid,
  created_at timestamptz not null default now(),
  constraint market_review_report_arrays_check check (
    jsonb_typeof(deterministic_issues) = 'array'
    and jsonb_typeof(semantic_issues) = 'array'
    and jsonb_typeof(editorial_notes) = 'array'
  )
);

create table if not exists private.market_admin_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  action_code text not null,
  draft_id uuid references private.market_drafts(id) on delete set null,
  market_id text,
  draft_version bigint,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint market_admin_audit_detail_check check (jsonb_typeof(detail) = 'object')
);

create index if not exists market_drafts_workflow_updated_idx
  on private.market_drafts (workflow_status, updated_at desc);
create index if not exists market_review_reports_draft_created_idx
  on private.market_review_reports (draft_id, created_at desc);
create index if not exists market_admin_audit_market_created_idx
  on private.market_admin_audit (market_id, created_at desc);

alter table private.market_drafts enable row level security;
alter table private.market_review_reports enable row level security;
alter table private.market_admin_audit enable row level security;

revoke all on table private.market_drafts from public, anon, authenticated;
revoke all on table private.market_review_reports from public, anon, authenticated;
revoke all on table private.market_admin_audit from public, anon, authenticated;
grant all on table private.market_drafts to postgres, service_role;
grant all on table private.market_review_reports to postgres, service_role;
grant all on table private.market_admin_audit to postgres, service_role;
grant usage, select on all sequences in schema private to postgres, service_role;

create or replace function private.require_current_admin()
returns uuid
language plpgsql
security definer
set search_path = ''
as $function$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from auth.users u
    where u.id = current_user_id
      and coalesce((u.raw_app_meta_data ->> 'oraklo_admin')::boolean, false) = true
  ) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  return current_user_id;
end;
$function$;

revoke all on function private.require_current_admin() from public, anon, authenticated;

create or replace function private.market_draft_fingerprint(draft private.market_drafts)
returns text
language sql
immutable
set search_path = ''
as $function$
  select md5(concat_ws(
    E'\n',
    coalesce(draft.market_slug, ''), coalesce(draft.question, ''),
    coalesce(draft.subject, ''), coalesce(draft.category, ''),
    coalesce(draft.yes_option, ''), coalesce(draft.no_option, ''),
    coalesce(draft.evaluation_period_label, ''),
    coalesce(extract(epoch from draft.evaluation_ends_at)::text, ''),
    coalesce(draft.timezone, ''),
    coalesce(extract(epoch from draft.resolution_deadline)::text, ''),
    coalesce(draft.yes_criteria, ''), coalesce(draft.no_criteria, ''),
    coalesce(draft.edge_cases, ''), coalesce(draft.primary_source::text, ''),
    coalesce(draft.alternative_sources::text, ''), coalesce(draft.delay_treatment, ''),
    coalesce(draft.cancellation_treatment, ''), coalesce(draft.leak_treatment, ''),
    coalesce(draft.rename_treatment, ''), coalesce(draft.assumptions, ''),
    coalesce(draft.public_criteria, '')
  ));
$function$;

revoke all on function private.market_draft_fingerprint(private.market_drafts)
  from public, anon, authenticated;

create or replace function private.market_draft_deterministic_issues(draft private.market_drafts)
returns jsonb
language plpgsql
stable
set search_path = ''
as $function$
declare
  issues jsonb := '[]'::jsonb;
  primary_url text := trim(coalesce(draft.primary_source ->> 'url', ''));
  alternative jsonb;
begin
  if length(trim(coalesce(draft.question, ''))) < 20 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'QUESTION_REQUIRED', 'field', 'question',
      'message', 'Escribe una pregunta completa y medible de al menos 20 caracteres.'
    ));
  end if;

  if coalesce(draft.question, '') ~* '\m(exito|éxito|importante|grande|pronto|el próximo|el proximo|el último|el ultimo|este evento)\M' then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'QUESTION_AMBIGUOUS_TERM', 'field', 'question',
      'message', 'La pregunta contiene un término relativo o subjetivo que necesita una métrica, fecha o edición concreta.'
    ));
  end if;

  if length(trim(coalesce(draft.subject, ''))) < 3 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'SUBJECT_REQUIRED', 'field', 'subject',
      'message', 'Identifica de forma inequívoca el sujeto, evento o producto.'
    ));
  end if;

  if length(trim(coalesce(draft.category, ''))) < 2 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'CATEGORY_REQUIRED', 'field', 'category',
      'message', 'Selecciona una categoría.'
    ));
  end if;

  if lower(trim(coalesce(draft.yes_option, ''))) = lower(trim(coalesce(draft.no_option, '')))
     or lower(trim(coalesce(draft.yes_option, ''))) not in ('sí', 'si')
     or lower(trim(coalesce(draft.no_option, ''))) <> 'no' then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'OPTIONS_NOT_BINARY', 'field', 'options',
      'message', 'Las opciones deben ser Sí y No, mutuamente excluyentes.'
    ));
  end if;

  if length(trim(coalesce(draft.evaluation_period_label, ''))) < 8
     or draft.evaluation_ends_at is null
     or draft.closes_at is null then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'PERIOD_REQUIRED', 'field', 'evaluation_period',
      'message', 'Define el periodo evaluado y su final exacto.'
    ));
  elsif draft.evaluation_ends_at <> draft.closes_at then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'TEMPORAL_CONTRADICTION', 'field', 'evaluation_ends_at',
      'message', 'El cierre de participación debe derivarse del final del periodo y no contradecirlo.'
    ));
  end if;

  if length(trim(coalesce(draft.timezone, ''))) < 3
     or not exists (
       select 1 from pg_catalog.pg_timezone_names tz where tz.name = draft.timezone
     ) then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'TIMEZONE_INVALID', 'field', 'timezone',
      'message', 'Selecciona una zona horaria IANA válida, por ejemplo Europe/Madrid.'
    ));
  end if;

  if draft.resolution_deadline is null
     or (draft.evaluation_ends_at is not null and draft.resolution_deadline < draft.evaluation_ends_at) then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'RESOLUTION_DEADLINE_INVALID', 'field', 'resolution_deadline',
      'message', 'La fecha límite de resolución debe ser posterior al final del periodo evaluado.'
    ));
  end if;

  if length(trim(coalesce(draft.yes_criteria, ''))) < 20 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'YES_CRITERIA_REQUIRED', 'field', 'yes_criteria',
      'message', 'Describe la prueba exacta que resuelve Sí.'
    ));
  end if;
  if length(trim(coalesce(draft.no_criteria, ''))) < 20 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'NO_CRITERIA_REQUIRED', 'field', 'no_criteria',
      'message', 'Describe la prueba exacta que resuelve No.'
    ));
  end if;
  if lower(trim(coalesce(draft.yes_criteria, ''))) = lower(trim(coalesce(draft.no_criteria, '')))
     and length(trim(coalesce(draft.yes_criteria, ''))) > 0 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'OPTIONS_OVERLAP', 'field', 'no_criteria',
      'message', 'Los criterios de Sí y No se solapan y permitirían dos resoluciones razonables.'
    ));
  end if;

  if length(trim(coalesce(draft.edge_cases, ''))) < 20 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'EDGE_CASES_REQUIRED', 'field', 'edge_cases',
      'message', 'Define los casos límite aplicables.'
    ));
  end if;

  if primary_url !~* '^https://'
     or primary_url ~* '^https://(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)' then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'PRIMARY_SOURCE_INVALID', 'field', 'primary_source',
      'message', 'Añade una fuente principal pública y verificable con URL HTTPS.'
    ));
  end if;

  if jsonb_array_length(coalesce(draft.alternative_sources, '[]'::jsonb)) < 1 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'ALTERNATIVE_SOURCE_REQUIRED', 'field', 'alternative_sources',
      'message', 'Añade al menos una fuente alternativa pública.'
    ));
  else
    for alternative in select value from jsonb_array_elements(draft.alternative_sources)
    loop
      if trim(coalesce(alternative ->> 'url', '')) !~* '^https://'
         or trim(coalesce(alternative ->> 'url', '')) ~* '^https://(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)' then
        issues := issues || jsonb_build_array(jsonb_build_object(
          'code', 'ALTERNATIVE_SOURCE_INVALID', 'field', 'alternative_sources',
          'message', 'Todas las fuentes alternativas deben usar una URL HTTPS pública.'
        ));
        exit;
      end if;
    end loop;
  end if;

  if length(trim(coalesce(draft.public_criteria, ''))) < 30 then
    issues := issues || jsonb_build_array(jsonb_build_object(
      'code', 'PUBLIC_CRITERIA_REQUIRED', 'field', 'public_criteria',
      'message', 'Explica públicamente cómo se resolverá el mercado.'
    ));
  end if;

  return issues;
end;
$function$;

revoke all on function private.market_draft_deterministic_issues(private.market_drafts)
  from public, anon, authenticated;

create or replace function public.save_market_draft(
  draft_id_input uuid,
  expected_version_input bigint,
  draft_input jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  draft_row private.market_drafts%rowtype;
  previous_fingerprint text;
  next_fingerprint text;
  issues jsonb;
  next_evaluation_end timestamptz;
  next_resolution_deadline timestamptz;
  next_slug text := lower(trim(coalesce(draft_input ->> 'market_slug', '')));
  was_created boolean := draft_id_input is null;
begin
  if jsonb_typeof(draft_input) <> 'object' then
    raise exception 'INVALID_DRAFT_PAYLOAD' using errcode = '22023';
  end if;
  if octet_length(draft_input::text) > 65536 then
    raise exception 'DRAFT_PAYLOAD_TOO_LARGE' using errcode = '22023';
  end if;

  if next_slug !~ '^[a-z0-9][a-z0-9-]{2,119}$' then
    raise exception 'INVALID_MARKET_SLUG' using errcode = '22023';
  end if;

  begin
    next_evaluation_end := nullif(trim(draft_input ->> 'evaluation_ends_at'), '')::timestamptz;
    next_resolution_deadline := nullif(trim(draft_input ->> 'resolution_deadline'), '')::timestamptz;
  exception when invalid_datetime_format then
    raise exception 'INVALID_DRAFT_DATE' using errcode = '22007';
  end;

  if draft_id_input is null then
    insert into private.market_drafts (
      market_slug, question, subject, category, yes_option, no_option,
      evaluation_period_label, evaluation_ends_at, closes_at, timezone,
      resolution_deadline, yes_criteria, no_criteria, edge_cases,
      primary_source, alternative_sources, delay_treatment,
      cancellation_treatment, leak_treatment, rename_treatment, assumptions,
      public_criteria, description, created_by, updated_by
    ) values (
      next_slug, nullif(trim(draft_input ->> 'question'), ''),
      nullif(trim(draft_input ->> 'subject'), ''), nullif(trim(draft_input ->> 'category'), ''),
      coalesce(nullif(trim(draft_input ->> 'yes_option'), ''), 'Sí'),
      coalesce(nullif(trim(draft_input ->> 'no_option'), ''), 'No'),
      nullif(trim(draft_input ->> 'evaluation_period_label'), ''),
      next_evaluation_end, next_evaluation_end, nullif(trim(draft_input ->> 'timezone'), ''),
      next_resolution_deadline, nullif(trim(draft_input ->> 'yes_criteria'), ''),
      nullif(trim(draft_input ->> 'no_criteria'), ''), nullif(trim(draft_input ->> 'edge_cases'), ''),
      coalesce(draft_input -> 'primary_source', '{}'::jsonb),
      coalesce(draft_input -> 'alternative_sources', '[]'::jsonb),
      nullif(trim(draft_input ->> 'delay_treatment'), ''),
      nullif(trim(draft_input ->> 'cancellation_treatment'), ''),
      nullif(trim(draft_input ->> 'leak_treatment'), ''),
      nullif(trim(draft_input ->> 'rename_treatment'), ''),
      nullif(trim(draft_input ->> 'assumptions'), ''),
      nullif(trim(draft_input ->> 'public_criteria'), ''),
      nullif(trim(draft_input ->> 'description'), ''), actor_id, actor_id
    ) returning * into draft_row;
  else
    select * into draft_row
    from private.market_drafts
    where id = draft_id_input
    for update;

    if not found then
      raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001';
    end if;
    if expected_version_input is null or expected_version_input <> draft_row.content_version then
      raise exception 'DRAFT_VERSION_MOVED' using errcode = '40001';
    end if;
    if draft_row.workflow_status in ('published', 'early_closed', 'cancelled', 'pending_resolution', 'resolved', 'annulled') then
      raise exception 'PUBLISHED_MARKET_FIELDS_LOCKED' using errcode = '22023';
    end if;

    previous_fingerprint := private.market_draft_fingerprint(draft_row);
    update private.market_drafts set
      market_slug = next_slug,
      question = nullif(trim(draft_input ->> 'question'), ''),
      subject = nullif(trim(draft_input ->> 'subject'), ''),
      category = nullif(trim(draft_input ->> 'category'), ''),
      yes_option = coalesce(nullif(trim(draft_input ->> 'yes_option'), ''), 'Sí'),
      no_option = coalesce(nullif(trim(draft_input ->> 'no_option'), ''), 'No'),
      evaluation_period_label = nullif(trim(draft_input ->> 'evaluation_period_label'), ''),
      evaluation_ends_at = next_evaluation_end,
      closes_at = next_evaluation_end,
      timezone = nullif(trim(draft_input ->> 'timezone'), ''),
      resolution_deadline = next_resolution_deadline,
      yes_criteria = nullif(trim(draft_input ->> 'yes_criteria'), ''),
      no_criteria = nullif(trim(draft_input ->> 'no_criteria'), ''),
      edge_cases = nullif(trim(draft_input ->> 'edge_cases'), ''),
      primary_source = coalesce(draft_input -> 'primary_source', '{}'::jsonb),
      alternative_sources = coalesce(draft_input -> 'alternative_sources', '[]'::jsonb),
      delay_treatment = nullif(trim(draft_input ->> 'delay_treatment'), ''),
      cancellation_treatment = nullif(trim(draft_input ->> 'cancellation_treatment'), ''),
      leak_treatment = nullif(trim(draft_input ->> 'leak_treatment'), ''),
      rename_treatment = nullif(trim(draft_input ->> 'rename_treatment'), ''),
      assumptions = nullif(trim(draft_input ->> 'assumptions'), ''),
      public_criteria = nullif(trim(draft_input ->> 'public_criteria'), ''),
      description = nullif(trim(draft_input ->> 'description'), ''),
      content_version = content_version + 1,
      updated_by = actor_id,
      updated_at = now()
    where id = draft_id_input
    returning * into draft_row;
  end if;

  next_fingerprint := private.market_draft_fingerprint(draft_row);
  issues := private.market_draft_deterministic_issues(draft_row);

  update private.market_drafts set
    content_fingerprint = next_fingerprint,
    workflow_status = case when jsonb_array_length(issues) = 0 then 'draft_ready' else 'draft_incomplete' end,
    review_status = case
      when was_created or previous_fingerprint is distinct from next_fingerprint then 'not_requested'
      else review_status
    end,
    reviewed_version = case
      when was_created or previous_fingerprint is distinct from next_fingerprint then null
      else reviewed_version
    end,
    reviewed_fingerprint = case
      when was_created or previous_fingerprint is distinct from next_fingerprint then null
      else reviewed_fingerprint
    end,
    human_confirmed_at = case
      when was_created or previous_fingerprint is distinct from next_fingerprint then null
      else human_confirmed_at
    end,
    human_confirmed_by = case
      when was_created or previous_fingerprint is distinct from next_fingerprint then null
      else human_confirmed_by
    end
  where id = draft_row.id
  returning * into draft_row;

  insert into private.market_admin_audit (
    actor_id, action_code, draft_id, draft_version, detail
  ) values (
    actor_id,
    case when was_created then 'DRAFT_CREATED'
      when previous_fingerprint is distinct from next_fingerprint then 'DRAFT_SAVED_REVIEW_INVALIDATED'
      else 'DRAFT_SAVED' end,
    draft_row.id, draft_row.content_version,
    jsonb_build_object('deterministic_issue_count', jsonb_array_length(issues))
  );

  return jsonb_build_object(
    'draft', to_jsonb(draft_row) - 'created_by' - 'updated_by' - 'human_confirmed_by',
    'deterministic_issues', issues
  );
end;
$function$;

revoke all on function public.save_market_draft(uuid, bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.save_market_draft(uuid, bigint, jsonb)
  to authenticated;

create or replace function public.list_admin_market_drafts(
  status_filter text default null,
  query_filter text default null,
  limit_count integer default 50,
  offset_count integer default 0
)
returns table (
  id uuid, market_id text, market_slug text, question text, category text,
  workflow_status text, review_status text, content_version bigint,
  scheduled_for timestamptz, updated_at timestamptz,
  participants_count integer, karma_total integer
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  perform private.require_current_admin();
  return query
  select
    d.id, d.market_id, d.market_slug, d.question, d.category,
    d.workflow_status, d.review_status, d.content_version,
    d.scheduled_for, d.updated_at,
    count(p.id)::integer,
    coalesce(sum(p.karma_risked), 0)::integer
  from private.market_drafts d
  left join public.predictions p on p.market_id = d.market_id
  where (status_filter is null or status_filter = '' or d.workflow_status = status_filter)
    and (
      query_filter is null or query_filter = ''
      or d.question ilike '%' || query_filter || '%'
      or d.market_slug ilike '%' || query_filter || '%'
    )
  group by d.id
  order by d.updated_at desc
  limit least(greatest(limit_count, 1), 100)
  offset greatest(offset_count, 0);
end;
$function$;

revoke all on function public.list_admin_market_drafts(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.list_admin_market_drafts(text, text, integer, integer)
  to authenticated;

create or replace function public.get_admin_market_draft(draft_id_input uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  draft_row private.market_drafts%rowtype;
begin
  perform private.require_current_admin();
  select * into draft_row from private.market_drafts where id = draft_id_input;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;

  return jsonb_build_object(
    'draft', to_jsonb(draft_row) - 'created_by' - 'updated_by' - 'human_confirmed_by',
    'deterministic_issues', private.market_draft_deterministic_issues(draft_row),
    'latest_review', (
      select to_jsonb(r) - 'reviewed_by'
      from private.market_review_reports r
      where r.draft_id = draft_id_input
      order by r.created_at desc limit 1
    ),
    'audit', coalesce((
      select jsonb_agg(to_jsonb(a) - 'actor_id' order by a.created_at desc)
      from (
        select * from private.market_admin_audit
        where draft_id = draft_id_input order by created_at desc limit 30
      ) a
    ), '[]'::jsonb)
  );
end;
$function$;

revoke all on function public.get_admin_market_draft(uuid)
  from public, anon, authenticated;
grant execute on function public.get_admin_market_draft(uuid) to authenticated;

create or replace function public.begin_market_draft_review(
  draft_id_input uuid,
  expected_version_input bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  draft_row private.market_drafts%rowtype;
  issues jsonb;
begin
  select * into draft_row from private.market_drafts
  where id = draft_id_input for update;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;
  if expected_version_input is null
     or draft_row.content_version <> expected_version_input then
    raise exception 'DRAFT_VERSION_MOVED' using errcode = '40001';
  end if;
  if draft_row.workflow_status in ('published', 'scheduled', 'cancelled', 'resolved', 'annulled') then
    raise exception 'DRAFT_REVIEW_NOT_ALLOWED' using errcode = '22023';
  end if;

  issues := private.market_draft_deterministic_issues(draft_row);
  if jsonb_array_length(issues) > 0 then
    insert into private.market_review_reports (
      draft_id, draft_version, content_fingerprint, validator_version,
      result, deterministic_issues, reviewed_by
    ) values (
      draft_row.id, draft_row.content_version, draft_row.content_fingerprint,
      'step13.4-deterministic-v1', 'rejected', issues, actor_id
    );
    update private.market_drafts set
      workflow_status = 'review_rejected', review_status = 'rejected',
      reviewed_version = null, reviewed_fingerprint = null,
      human_confirmed_at = null, human_confirmed_by = null,
      updated_at = now(), updated_by = actor_id
    where id = draft_row.id;
    insert into private.market_admin_audit (
      actor_id, action_code, draft_id, draft_version, detail
    ) values (
      actor_id, 'REVIEW_REJECTED_DETERMINISTIC', draft_row.id,
      draft_row.content_version, jsonb_build_object('blocking_reasons', issues)
    );
    return jsonb_build_object('status', 'rejected', 'blocking_reasons', issues);
  end if;

  update private.market_drafts set
    workflow_status = 'review_in_progress', review_status = 'in_progress',
    updated_at = now(), updated_by = actor_id
  where id = draft_row.id returning * into draft_row;

  insert into private.market_admin_audit (
    actor_id, action_code, draft_id, draft_version
  ) values (actor_id, 'REVIEW_STARTED', draft_row.id, draft_row.content_version);

  return jsonb_build_object(
    'status', 'in_progress',
    'draft', to_jsonb(draft_row) - 'created_by' - 'updated_by' - 'human_confirmed_by'
  );
end;
$function$;

revoke all on function public.begin_market_draft_review(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.begin_market_draft_review(uuid, bigint)
  to authenticated;

create or replace function public.record_market_draft_review(
  draft_id_input uuid,
  draft_version_input bigint,
  content_fingerprint_input text,
  validator_version_input text,
  result_input text,
  semantic_issues_input jsonb,
  editorial_notes_input jsonb,
  reviewed_by_input uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  draft_row private.market_drafts%rowtype;
  normalized_result text := lower(trim(coalesce(result_input, '')));
  next_workflow text;
begin
  if normalized_result not in (
    'approved', 'rejected', 'inconclusive', 'service_unavailable',
    'quota_exhausted', 'invalid_response'
  ) then raise exception 'INVALID_REVIEW_RESULT' using errcode = '22023'; end if;
  if jsonb_typeof(coalesce(semantic_issues_input, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(editorial_notes_input, '[]'::jsonb)) <> 'array' then
    raise exception 'INVALID_REVIEW_REPORT' using errcode = '22023';
  end if;

  select * into draft_row from private.market_drafts
  where id = draft_id_input for update;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;
  if draft_row.workflow_status <> 'review_in_progress'
     or draft_version_input is null
     or draft_row.content_version <> draft_version_input
     or content_fingerprint_input is null
     or draft_row.content_fingerprint is distinct from content_fingerprint_input then
    raise exception 'REVIEW_VERSION_MOVED' using errcode = '40001';
  end if;
  if normalized_result = 'approved'
     and jsonb_array_length(coalesce(semantic_issues_input, '[]'::jsonb)) > 0 then
    raise exception 'APPROVED_REVIEW_HAS_BLOCKERS' using errcode = '22023';
  end if;

  next_workflow := case normalized_result
    when 'approved' then 'review_approved'
    when 'rejected' then 'review_rejected'
    when 'inconclusive' then 'review_inconclusive'
    else 'review_unavailable'
  end;

  insert into private.market_review_reports (
    draft_id, draft_version, content_fingerprint, validator_version,
    result, semantic_issues, editorial_notes, reviewed_by
  ) values (
    draft_row.id, draft_row.content_version, draft_row.content_fingerprint,
    left(trim(validator_version_input), 100), normalized_result,
    coalesce(semantic_issues_input, '[]'::jsonb),
    coalesce(editorial_notes_input, '[]'::jsonb), reviewed_by_input
  );

  update private.market_drafts set
    workflow_status = next_workflow,
    review_status = normalized_result,
    reviewed_version = case when normalized_result = 'approved' then content_version else null end,
    reviewed_fingerprint = case when normalized_result = 'approved' then content_fingerprint else null end,
    human_confirmed_at = null, human_confirmed_by = null,
    updated_at = now(), updated_by = coalesce(reviewed_by_input, updated_by)
  where id = draft_row.id returning * into draft_row;

  insert into private.market_admin_audit (
    actor_id, action_code, draft_id, draft_version, detail
  ) values (
    reviewed_by_input, 'REVIEW_' || upper(normalized_result), draft_row.id,
    draft_row.content_version,
    jsonb_build_object('blocking_reasons', coalesce(semantic_issues_input, '[]'::jsonb))
  );

  return jsonb_build_object(
    'status', normalized_result,
    'workflow_status', draft_row.workflow_status,
    'draft_version', draft_row.content_version
  );
end;
$function$;

revoke all on function public.record_market_draft_review(
  uuid, bigint, text, text, text, jsonb, jsonb, uuid
) from public, anon, authenticated;
grant execute on function public.record_market_draft_review(
  uuid, bigint, text, text, text, jsonb, jsonb, uuid
) to service_role;

create or replace function public.confirm_market_draft_review(
  draft_id_input uuid,
  expected_version_input bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  draft_row private.market_drafts%rowtype;
begin
  select * into draft_row from private.market_drafts
  where id = draft_id_input for update;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;
  if expected_version_input is null
     or draft_row.content_version <> expected_version_input
     or draft_row.review_status <> 'approved'
     or draft_row.reviewed_version <> draft_row.content_version
     or draft_row.reviewed_fingerprint is distinct from private.market_draft_fingerprint(draft_row) then
    raise exception 'CURRENT_APPROVAL_REQUIRED' using errcode = '22023';
  end if;

  update private.market_drafts set
    workflow_status = 'human_confirmed', human_confirmed_at = now(),
    human_confirmed_by = actor_id, updated_at = now(), updated_by = actor_id
  where id = draft_row.id returning * into draft_row;

  insert into private.market_admin_audit (
    actor_id, action_code, draft_id, draft_version
  ) values (actor_id, 'HUMAN_CONFIRMATION_RECORDED', draft_row.id, draft_row.content_version);

  return jsonb_build_object('status', draft_row.workflow_status, 'confirmed_at', draft_row.human_confirmed_at);
end;
$function$;

revoke all on function public.confirm_market_draft_review(uuid, bigint)
  from public, anon, authenticated;
grant execute on function public.confirm_market_draft_review(uuid, bigint)
  to authenticated;

create or replace function private.materialize_market_draft(
  draft_id_input uuid,
  actor_id_input uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  draft_row private.market_drafts%rowtype;
begin
  if actor_id_input is null or not exists (
    select 1
    from auth.users u
    where u.id = actor_id_input
      and coalesce((u.raw_app_meta_data ->> 'oraklo_admin')::boolean, false) = true
  ) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  select * into draft_row from private.market_drafts
  where id = draft_id_input for update;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;
  if draft_row.review_status <> 'approved'
     or draft_row.reviewed_version <> draft_row.content_version
     or draft_row.reviewed_fingerprint is distinct from private.market_draft_fingerprint(draft_row)
     or draft_row.human_confirmed_at is null then
    raise exception 'CURRENT_APPROVAL_AND_CONFIRMATION_REQUIRED' using errcode = '22023';
  end if;
  if draft_row.evaluation_ends_at is null or draft_row.evaluation_ends_at <= now() then
    raise exception 'MARKET_PERIOD_ALREADY_ENDED' using errcode = '22023';
  end if;
  if draft_row.market_id is not null then
    raise exception 'MARKET_ALREADY_PUBLISHED' using errcode = '22023';
  end if;

  insert into public.markets (
    id, question, category, status, yes_percent, no_percent, difficulty,
    close_label, closes_at, description, resolution_source, yes_criteria,
    no_criteria, edge_case, highlighted, popularity,
    evaluation_ends_at, evaluation_timezone, resolution_deadline,
    market_definition_version
  ) values (
    draft_row.market_slug, draft_row.question, draft_row.category, 'Abierto',
    50, 50, 'Normal',
    'Cierra ' || to_char(draft_row.evaluation_ends_at at time zone draft_row.timezone, 'DD Mon YYYY · HH24:MI'),
    draft_row.evaluation_ends_at,
    coalesce(draft_row.description, draft_row.public_criteria),
    coalesce(draft_row.primary_source ->> 'url', ''),
    draft_row.yes_criteria, draft_row.no_criteria, draft_row.edge_cases,
    false, 0, draft_row.evaluation_ends_at, draft_row.timezone,
    draft_row.resolution_deadline, draft_row.content_version
  );

  update private.market_drafts set
    market_id = market_slug, workflow_status = 'published',
    published_at = now(), published_by = actor_id_input,
    scheduled_for = null, updated_at = now(), updated_by = actor_id_input
  where id = draft_row.id returning * into draft_row;

  insert into private.market_admin_audit (
    actor_id, action_code, draft_id, market_id, draft_version
  ) values (
    actor_id_input, 'MARKET_PUBLISHED', draft_row.id,
    draft_row.market_id, draft_row.content_version
  );

  return jsonb_build_object(
    'status', 'published', 'market_id', draft_row.market_id,
    'published_at', draft_row.published_at
  );
end;
$function$;

revoke all on function private.materialize_market_draft(uuid, uuid)
  from public, anon, authenticated;

create or replace function public.publish_market_draft(
  draft_id_input uuid,
  expected_version_input bigint,
  scheduled_for_input timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  draft_row private.market_drafts%rowtype;
begin
  select * into draft_row from private.market_drafts
  where id = draft_id_input for update;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;
  if expected_version_input is null
     or draft_row.content_version <> expected_version_input then
    raise exception 'DRAFT_VERSION_MOVED' using errcode = '40001';
  end if;
  if draft_row.review_status <> 'approved'
     or draft_row.reviewed_version <> draft_row.content_version
     or draft_row.reviewed_fingerprint is distinct from private.market_draft_fingerprint(draft_row)
     or draft_row.human_confirmed_at is null then
    raise exception 'CURRENT_APPROVAL_AND_CONFIRMATION_REQUIRED' using errcode = '22023';
  end if;

  if scheduled_for_input is not null and scheduled_for_input > now() then
    if scheduled_for_input >= draft_row.evaluation_ends_at then
      raise exception 'SCHEDULE_AFTER_MARKET_CLOSE' using errcode = '22023';
    end if;
    update private.market_drafts set
      workflow_status = 'scheduled', scheduled_for = scheduled_for_input,
      updated_at = now(), updated_by = actor_id
    where id = draft_row.id returning * into draft_row;
    insert into private.market_admin_audit (
      actor_id, action_code, draft_id, draft_version, detail
    ) values (
      actor_id, 'MARKET_SCHEDULED', draft_row.id, draft_row.content_version,
      jsonb_build_object('scheduled_for', scheduled_for_input)
    );
    return jsonb_build_object('status', 'scheduled', 'scheduled_for', scheduled_for_input);
  end if;

  return private.materialize_market_draft(draft_id_input, actor_id);
end;
$function$;

revoke all on function public.publish_market_draft(uuid, bigint, timestamptz)
  from public, anon, authenticated;
grant execute on function public.publish_market_draft(uuid, bigint, timestamptz)
  to authenticated;

create or replace function public.publish_due_market_drafts(limit_count integer default 20)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  draft_row private.market_drafts%rowtype;
  published jsonb := '[]'::jsonb;
  failed jsonb := '[]'::jsonb;
begin
  for draft_row in
    select * from private.market_drafts
    where workflow_status = 'scheduled' and scheduled_for <= now()
    order by scheduled_for for update skip locked
    limit least(greatest(limit_count, 1), 100)
  loop
    begin
      published := published || jsonb_build_array(
        private.materialize_market_draft(draft_row.id, draft_row.human_confirmed_by)
      );
    exception when others then
      failed := failed || jsonb_build_array(jsonb_build_object(
        'draft_id', draft_row.id, 'code', sqlstate
      ));
    end;
  end loop;
  return jsonb_build_object('published', published, 'failed', failed);
end;
$function$;

revoke all on function public.publish_due_market_drafts(integer)
  from public, anon, authenticated;
grant execute on function public.publish_due_market_drafts(integer) to service_role;

create or replace function public.close_market_participation_early(
  market_id_input text,
  reason_input text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  market_row public.markets%rowtype;
begin
  if length(trim(coalesce(reason_input, ''))) < 20 then
    raise exception 'EARLY_CLOSE_REASON_REQUIRED' using errcode = '22023';
  end if;
  select * into market_row from public.markets where id = market_id_input for update;
  if not found then raise exception 'MARKET_NOT_FOUND' using errcode = 'P0001'; end if;
  if market_row.status <> 'Abierto' then
    raise exception 'MARKET_NOT_OPEN' using errcode = '22023';
  end if;

  update public.markets set
    status = 'Cerrado', close_label = 'Cerrado anticipadamente · pendiente de resolución',
    participation_closed_at = now(), participation_close_reason = trim(reason_input)
  where id = market_id_input;
  update private.market_drafts set
    workflow_status = 'early_closed', updated_at = now(), updated_by = actor_id
  where market_id = market_id_input;
  insert into private.market_admin_audit (
    actor_id, action_code, market_id, detail
  ) values (
    actor_id, 'PARTICIPATION_CLOSED_EARLY', market_id_input,
    jsonb_build_object(
      'reason', trim(reason_input),
      'evaluation_ends_at', market_row.evaluation_ends_at,
      'original_closes_at', market_row.closes_at
    )
  );
  return jsonb_build_object(
    'status', 'closed_early', 'market_id', market_id_input,
    'participation_closed_at', now(),
    'evaluation_ends_at', market_row.evaluation_ends_at
  );
end;
$function$;

revoke all on function public.close_market_participation_early(text, text)
  from public, anon, authenticated;
grant execute on function public.close_market_participation_early(text, text)
  to authenticated;

create or replace function public.cancel_market_safely(
  market_id_input text,
  reason_input text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id uuid := private.require_current_admin();
  resolution_summary jsonb;
begin
  if length(trim(coalesce(reason_input, ''))) < 20 then
    raise exception 'CANCELLATION_REASON_REQUIRED' using errcode = '22023';
  end if;

  resolution_summary := public.resolve_market(
    market_id_input, 'Anulado', trim(reason_input)
  );
  update private.market_drafts set
    workflow_status = 'annulled', updated_at = now(), updated_by = actor_id
  where market_id = market_id_input;
  insert into private.market_admin_audit (
    actor_id, action_code, market_id, detail
  ) values (
    actor_id, 'MARKET_CANCELLED_AND_REFUNDED', market_id_input,
    jsonb_build_object('reason', trim(reason_input), 'resolution', resolution_summary)
  );
  return resolution_summary || jsonb_build_object(
    'status', 'annulled',
    'message', 'El Karma se ha devuelto atómicamente y el Prestigio no ha cambiado.'
  );
end;
$function$;

revoke all on function public.cancel_market_safely(text, text)
  from public, anon, authenticated;
grant execute on function public.cancel_market_safely(text, text)
  to authenticated;

create or replace function public.get_admin_market_for_resolution(
  market_id_input text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  market_row public.markets%rowtype;
begin
  perform private.require_current_admin();
  select * into market_row from public.markets where id = market_id_input;
  if not found then raise exception 'MARKET_NOT_FOUND' using errcode = 'P0001'; end if;

  return jsonb_build_object(
    'id', market_row.id,
    'question', market_row.question,
    'description', market_row.description,
    'status', market_row.status,
    'closes_at', market_row.closes_at,
    'evaluation_ends_at', market_row.evaluation_ends_at,
    'evaluation_timezone', market_row.evaluation_timezone,
    'resolution_deadline', market_row.resolution_deadline,
    'participation_closed_at', market_row.participation_closed_at,
    'participation_close_reason', market_row.participation_close_reason,
    'resolution_source', market_row.resolution_source,
    'yes_criteria', market_row.yes_criteria,
    'no_criteria', market_row.no_criteria,
    'edge_case', market_row.edge_case,
    'market_definition_version', market_row.market_definition_version,
    'resolution_result', market_row.resolution_result
  );
end;
$function$;

revoke all on function public.get_admin_market_for_resolution(text)
  from public, anon, authenticated;
grant execute on function public.get_admin_market_for_resolution(text)
  to authenticated;

create or replace function public.get_admin_market_catalog()
returns table (
  market_id text, question text, category text, status text,
  closes_at timestamptz, evaluation_ends_at timestamptz,
  resolution_deadline timestamptz, participation_closed_at timestamptz,
  participants_count integer, karma_total integer,
  draft_id uuid, workflow_status text
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  perform private.require_current_admin();
  return query
  select
    m.id, m.question, m.category, m.status, m.closes_at,
    m.evaluation_ends_at, m.resolution_deadline, m.participation_closed_at,
    count(p.id)::integer, coalesce(sum(p.karma_risked), 0)::integer,
    d.id, d.workflow_status
  from public.markets m
  left join public.predictions p on p.market_id = m.id
  left join private.market_drafts d on d.market_id = m.id
  group by m.id, d.id
  order by m.created_at desc;
end;
$function$;

revoke all on function public.get_admin_market_catalog()
  from public, anon, authenticated;
grant execute on function public.get_admin_market_catalog() to authenticated;

create or replace function public.get_admin_market_audit(limit_count integer default 100)
returns table (
  action_code text, draft_id uuid, market_id text,
  draft_version bigint, detail jsonb, created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  perform private.require_current_admin();
  return query
  select a.action_code, a.draft_id, a.market_id, a.draft_version, a.detail, a.created_at
  from private.market_admin_audit a
  order by a.created_at desc
  limit least(greatest(limit_count, 1), 500);
end;
$function$;

revoke all on function public.get_admin_market_audit(integer)
  from public, anon, authenticated;
grant execute on function public.get_admin_market_audit(integer) to authenticated;

comment on function public.save_market_draft(uuid, bigint, jsonb) is
  'Guarda borradores privados y anula automáticamente cualquier aprobación al cambiar campos esenciales.';
comment on function public.publish_market_draft(uuid, bigint, timestamptz) is
  'Publica o programa solo con revisión vigente y confirmación humana; revalida rol, versión y huella.';
comment on function public.cancel_market_safely(text, text) is
  'Anula con devolución atómica de Karma, Prestigio sin cambios y auditoría administrativa.';

commit;
