begin;

-- The historical fact-check ledger remains append-only for auditability, but it
-- no longer decides whether a future provider market may enter the Editor.
drop trigger if exists zzzz_authoritative_radar_fact_gate_v2_before_write
  on private.external_market_candidates;
drop trigger if exists aaaa_market_draft_radar_fact_publication_gate_v1
  on private.market_drafts;

alter table private.external_market_candidates
  add column if not exists eligibility_status text,
  add column if not exists eligibility_reason_code text,
  add column if not exists eligibility_reason text,
  add column if not exists eligibility_checked_at timestamptz,
  add column if not exists eligibility_expires_at timestamptz,
  add column if not exists eligibility_policy_version text,
  add column if not exists eligibility_evidence jsonb not null default '[]'::jsonb,
  add column if not exists current_eligibility_check_id bigint;

create table if not exists private.market_radar_eligibility_checks (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null unique,
  candidate_id uuid not null
    references private.external_market_candidates(id) on delete restrict,
  provider text not null,
  external_id text not null,
  event_group_key text,
  policy_version text not null,
  status text not null,
  reason_code text,
  reason text,
  evidence jsonb not null default '[]'::jsonb,
  checked_at timestamptz not null,
  expires_at timestamptz not null,
  decision_hash text not null,
  created_at timestamptz not null default now(),
  constraint market_radar_eligibility_checks_provider_check
    check (provider in ('polymarket', 'kalshi', 'tavily')),
  constraint market_radar_eligibility_checks_status_check
    check (status in ('eligible', 'terminal', 'inactive_option', 'technical_hold', 'invalid', 'duplicate')),
  constraint market_radar_eligibility_checks_policy_check
    check (policy_version = 'atinara-prediction-policy-v5'),
  constraint market_radar_eligibility_checks_evidence_check
    check (jsonb_typeof(evidence) = 'array' and jsonb_array_length(evidence) <= 12),
  constraint market_radar_eligibility_checks_hash_check
    check (decision_hash ~ '^[0-9a-f]{64}$'),
  constraint market_radar_eligibility_checks_dates_check
    check (expires_at > checked_at)
);

create index if not exists market_radar_eligibility_checks_candidate_idx
  on private.market_radar_eligibility_checks(candidate_id, checked_at desc, id desc);
create index if not exists market_radar_eligibility_checks_event_idx
  on private.market_radar_eligibility_checks(event_group_key, checked_at desc)
  where event_group_key is not null;

create table if not exists private.market_radar_eligibility_attempts (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null unique,
  candidate_id uuid not null
    references private.external_market_candidates(id) on delete restrict,
  preparation_revision bigint not null,
  purpose text not null,
  phase text not null,
  status text not null default 'technical_failure',
  error_code text not null,
  retryable boolean not null,
  state_preserved boolean not null default true,
  created_at timestamptz not null default now(),
  constraint market_radar_eligibility_attempts_purpose_check
    check (purpose in ('prepare', 'revalidate')),
  constraint market_radar_eligibility_attempts_phase_check
    check (phase in ('provider_revalidation', 'official_terminal_scan', 'eligibility_persistence')),
  constraint market_radar_eligibility_attempts_status_check
    check (status = 'technical_failure'),
  constraint market_radar_eligibility_attempts_error_check
    check (error_code ~ '^[A-Z][A-Z0-9_]{2,100}$')
);

create index if not exists market_radar_eligibility_attempts_candidate_idx
  on private.market_radar_eligibility_attempts(candidate_id, created_at desc, id desc);

do $block$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'private.external_market_candidates'::regclass
      and conname = 'external_market_candidates_current_eligibility_check_fk'
  ) then
    alter table private.external_market_candidates
      add constraint external_market_candidates_current_eligibility_check_fk
      foreign key (current_eligibility_check_id)
      references private.market_radar_eligibility_checks(id) on delete restrict;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'private.external_market_candidates'::regclass
      and conname = 'external_market_candidates_eligibility_status_check'
  ) then
    alter table private.external_market_candidates
      add constraint external_market_candidates_eligibility_status_check check (
        eligibility_status is null or eligibility_status in (
          'eligible', 'terminal', 'inactive_option', 'technical_hold', 'invalid', 'duplicate'
        )
      );
  end if;
end;
$block$;

create index if not exists external_market_candidates_current_eligibility_idx
  on private.external_market_candidates(current_eligibility_check_id)
  where current_eligibility_check_id is not null;
create index if not exists external_market_candidates_visible_eligibility_idx
  on private.external_market_candidates(
    eligibility_policy_version, eligibility_status, state, eligibility_expires_at desc
  );

revoke all privileges on table private.market_radar_eligibility_checks
  from public, anon, authenticated, service_role;
revoke all privileges on sequence private.market_radar_eligibility_checks_id_seq
  from public, anon, authenticated, service_role;
revoke all privileges on table private.market_radar_eligibility_attempts
  from public, anon, authenticated, service_role;
revoke all privileges on sequence private.market_radar_eligibility_attempts_id_seq
  from public, anon, authenticated, service_role;

create or replace function private.reject_market_radar_eligibility_check_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  raise exception 'RADAR_ELIGIBILITY_APPEND_ONLY' using errcode = '55000';
end;
$function$;

revoke all on function private.reject_market_radar_eligibility_check_mutation()
  from public, anon, authenticated, service_role;

drop trigger if exists reject_market_radar_eligibility_check_mutation
  on private.market_radar_eligibility_checks;
create trigger reject_market_radar_eligibility_check_mutation
before update or delete on private.market_radar_eligibility_checks
for each row execute function private.reject_market_radar_eligibility_check_mutation();

drop trigger if exists reject_market_radar_eligibility_attempt_mutation
  on private.market_radar_eligibility_attempts;
create trigger reject_market_radar_eligibility_attempt_mutation
before update or delete on private.market_radar_eligibility_attempts
for each row execute function private.reject_market_radar_eligibility_check_mutation();

-- One auditable bootstrap decision per existing row. This does not alter
-- markets, drafts, predictions, balances, LMSR, prices or settlements.
with classified as (
  select
    candidate.id,
    gen_random_uuid() as attempt_id,
    case
      when candidate.verification_status = 'rejected_resolved'
        or candidate.fact_status = 'fully_resolved' then 'terminal'
      when candidate.verification_status = 'rejected_duplicate' then 'duplicate'
      when candidate.verification_reason_code in ('PROVIDER_NOT_OPEN', 'PROVIDER_OPTION_INACTIVE')
        then 'inactive_option'
      when candidate.verification_status = 'rejected_invalid_source' then 'invalid'
      when candidate.verification_status = 'verified_open'
        and candidate.state in ('available', 'needs_review', 'prepared', 'dismissed')
        then 'technical_hold'
      else 'technical_hold'
    end as status,
    clock_timestamp() as checked_at
  from private.external_market_candidates candidate
  where candidate.current_eligibility_check_id is null
), inserted as (
  insert into private.market_radar_eligibility_checks (
    attempt_id, candidate_id, provider, external_id, event_group_key,
    policy_version, status, reason_code, reason, evidence,
    checked_at, expires_at, decision_hash
  )
  select
    classified.attempt_id,
    candidate.id,
    candidate.provider,
    candidate.external_id,
    candidate.event_group_key,
    'atinara-prediction-policy-v5',
    classified.status,
    case
      when classified.status = 'technical_hold' then 'ELIGIBILITY_REFRESH_REQUIRED'
      when classified.status = 'eligible' then null
      else coalesce(candidate.verification_reason_code, 'ELIGIBILITY_BOOTSTRAP_HOLD')
    end,
    case
      when classified.status = 'technical_hold'
        then 'El estado histórico se conservó, pero no concede una autorización nueva. El Radar debe revalidar la candidata.'
      when classified.status = 'eligible'
        then 'Candidata futura migrada a la puerta determinista de elegibilidad.'
      else coalesce(candidate.verification_reason, 'La candidata no está disponible para preparación.')
    end,
    case when classified.status = 'terminal' then coalesce((
      select jsonb_agg(evidence_item.value order by evidence_item.ordinality)
      from jsonb_array_elements(coalesce(candidate.verification_evidence, '[]'::jsonb))
        with ordinality as evidence_item(value, ordinality)
      where evidence_item.ordinality <= 12
    ), '[]'::jsonb) else '[]'::jsonb end,
    classified.checked_at,
    classified.checked_at + case
      when classified.status = 'technical_hold' then interval '5 minutes'
      else interval '6 hours'
    end,
    encode(extensions.digest(convert_to(
      concat_ws('|', candidate.provider, candidate.external_id, classified.status,
        coalesce(candidate.verification_reason_code, ''), classified.checked_at::text),
      'UTF8'
    ), 'sha256'), 'hex')
  from classified
  join private.external_market_candidates candidate on candidate.id = classified.id
  returning id, candidate_id, status, reason_code, reason, evidence, checked_at, expires_at
)
update private.external_market_candidates candidate set
  current_eligibility_check_id = inserted.id,
  eligibility_status = inserted.status,
  eligibility_reason_code = inserted.reason_code,
  eligibility_reason = inserted.reason,
  eligibility_evidence = inserted.evidence,
  eligibility_checked_at = inserted.checked_at,
  eligibility_expires_at = inserted.expires_at,
  eligibility_policy_version = 'atinara-prediction-policy-v5'
from inserted
where candidate.id = inserted.candidate_id;

create or replace function private.enforce_market_radar_eligibility_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  payload jsonb := coalesce(new.normalized_payload, '{}'::jsonb);
  payload_status text := nullif(payload ->> 'eligibility_status', '');
  payload_checked_at timestamptz;
  payload_expires_at timestamptz;
begin
  if payload_status is not null then
    begin
      payload_checked_at := nullif(payload ->> 'eligibility_checked_at', '')::timestamptz;
      payload_expires_at := nullif(payload ->> 'eligibility_expires_at', '')::timestamptz;
    exception when invalid_text_representation or datetime_field_overflow then
      raise exception 'INVALID_RADAR_ELIGIBILITY_DATE' using errcode = '22007';
    end;
    if payload ->> 'eligibility_policy_version' is distinct from 'atinara-prediction-policy-v5'
       or payload_status not in ('eligible', 'terminal', 'inactive_option', 'technical_hold', 'invalid', 'duplicate')
       or payload_checked_at is null
       or payload_expires_at is null
       or payload_expires_at <= payload_checked_at
       or jsonb_typeof(coalesce(payload -> 'eligibility_evidence', '[]'::jsonb)) <> 'array'
       or jsonb_array_length(coalesce(payload -> 'eligibility_evidence', '[]'::jsonb)) > 12 then
      raise exception 'INVALID_RADAR_ELIGIBILITY' using errcode = '22023';
    end if;
    new.eligibility_status := payload_status;
    new.eligibility_reason_code := nullif(left(payload ->> 'eligibility_reason_code', 100), '');
    new.eligibility_reason := nullif(left(payload ->> 'eligibility_reason', 1000), '');
    new.eligibility_checked_at := payload_checked_at;
    new.eligibility_expires_at := payload_expires_at;
    new.eligibility_policy_version := 'atinara-prediction-policy-v5';
    new.eligibility_evidence := coalesce(payload -> 'eligibility_evidence', '[]'::jsonb);
  end if;

  if new.eligibility_policy_version = 'atinara-prediction-policy-v5' then
    if new.eligibility_status = 'eligible' then
      new.verification_status := 'verified_open';
      new.quality_status := 'fit';
      if new.state not in ('prepared', 'dismissed') then new.state := 'available'; end if;
      new.verification_reason_code := null;
    elsif new.eligibility_status = 'terminal' then
      new.verification_status := 'rejected_resolved';
      new.quality_status := 'rejected';
      if new.state <> 'dismissed' then new.state := 'rejected'; end if;
      new.verification_reason_code := coalesce(new.eligibility_reason_code, 'EVENT_ALREADY_RESOLVED');
    elsif new.eligibility_status = 'duplicate' then
      new.verification_status := 'rejected_duplicate';
      new.quality_status := 'rejected';
      if new.state <> 'dismissed' then new.state := 'rejected'; end if;
      new.verification_reason_code := 'DUPLICATE_MARKET';
    elsif new.eligibility_status = 'invalid' then
      new.verification_status := 'rejected_invalid_source';
      new.quality_status := 'rejected';
      if new.state <> 'dismissed' then new.state := 'rejected'; end if;
    else
      new.verification_status := 'rejected_ineligible';
      new.quality_status := 'rejected';
      if new.state <> 'dismissed' then new.state := 'rejected'; end if;
    end if;
    new.verification_reason := new.eligibility_reason;
    new.verified_at := new.eligibility_checked_at;
    new.verification_expires_at := new.eligibility_expires_at;
    new.verification_evidence := new.eligibility_evidence;
    new.fact_status := null;
    new.fact_policy_version := null;
    new.fact_context_fingerprint := null;
    new.fact_checked_at := null;
    new.fact_check_expires_at := null;
    new.fact_check_purpose := null;
    new.current_fact_check_id := null;
  end if;
  return new;
end;
$function$;

revoke all on function private.enforce_market_radar_eligibility_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists zzzz_market_radar_eligibility_v1_before_write
  on private.external_market_candidates;
create trigger zzzz_market_radar_eligibility_v1_before_write
before insert or update on private.external_market_candidates
for each row execute function private.enforce_market_radar_eligibility_v1();

create or replace function private.market_radar_eligibility_payload(
  candidate private.external_market_candidates
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  select private.market_radar_safe_payload(candidate) || jsonb_build_object(
    'eligibility_status', candidate.eligibility_status,
    'eligibility_reason_code', candidate.eligibility_reason_code,
    'eligibility_reason', candidate.eligibility_reason,
    'eligibility_checked_at', candidate.eligibility_checked_at,
    'eligibility_expires_at', candidate.eligibility_expires_at,
    'eligibility_policy_version', candidate.eligibility_policy_version,
    'eligibility_evidence', candidate.eligibility_evidence,
    'current_eligibility_check_id', candidate.current_eligibility_check_id
  );
$function$;

revoke all on function private.market_radar_eligibility_payload(private.external_market_candidates)
  from public, anon, authenticated, service_role;

create or replace function public.record_market_radar_eligibility_attempt_v1(
  candidate_id_input uuid,
  expected_preparation_revision_input bigint,
  purpose_input text,
  attempt_id_input uuid,
  phase_input text,
  error_code_input text,
  retryable_input boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
  attempt private.market_radar_eligibility_attempts%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if attempt_id_input is null
     or purpose_input not in ('prepare', 'revalidate')
     or phase_input not in ('provider_revalidation', 'official_terminal_scan', 'eligibility_persistence')
     or coalesce(error_code_input, '') !~ '^[A-Z][A-Z0-9_]{2,100}$' then
    raise exception 'INVALID_RADAR_ELIGIBILITY_ATTEMPT' using errcode = '22023';
  end if;

  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input
  for share;
  if not found then raise exception 'RADAR_CANDIDATE_NOT_FOUND' using errcode = 'P0001'; end if;
  if candidate.preparation_revision is distinct from expected_preparation_revision_input then
    raise exception 'PREPARATION_REVISION_MISMATCH' using errcode = '40001';
  end if;

  insert into private.market_radar_eligibility_attempts(
    attempt_id, candidate_id, preparation_revision, purpose, phase,
    error_code, retryable, state_preserved
  ) values (
    attempt_id_input, candidate.id, candidate.preparation_revision, purpose_input,
    phase_input, error_code_input, coalesce(retryable_input, false), true
  ) on conflict (attempt_id) do nothing;

  select * into attempt
  from private.market_radar_eligibility_attempts attempt_alias
  where attempt_alias.attempt_id = attempt_id_input;
  if not found
     or attempt.candidate_id is distinct from candidate.id
     or attempt.preparation_revision is distinct from candidate.preparation_revision
     or attempt.purpose is distinct from purpose_input
     or attempt.phase is distinct from phase_input
     or attempt.error_code is distinct from error_code_input then
    raise exception 'RADAR_ELIGIBILITY_ATTEMPT_CONFLICT' using errcode = '40001';
  end if;

  return jsonb_build_object(
    'ok', true,
    'attempt_id', attempt.attempt_id,
    'attempt_record_id', attempt.id,
    'state_preserved', true,
    'authoritative_pointer_unchanged', true,
    'preparation_revision', candidate.preparation_revision,
    'idempotent', true
  );
end;
$function$;

revoke all on function public.record_market_radar_eligibility_attempt_v1(
  uuid,bigint,text,uuid,text,text,boolean
) from public, anon, authenticated;
grant execute on function public.record_market_radar_eligibility_attempt_v1(
  uuid,bigint,text,uuid,text,text,boolean
) to service_role;

create or replace function public.upsert_market_radar_batch_with_eligibility_v1(
  provider_input text,
  cache_key_input text,
  normalizer_version_input text,
  candidates_input jsonb,
  eligibility_checks_input jsonb,
  eligibility_policy_version_input text,
  provider_status_input jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  item jsonb;
  check_item jsonb;
  item_ordinality bigint;
  candidate private.external_market_candidates%rowtype;
  check_row private.market_radar_eligibility_checks%rowtype;
  accepted_count_value integer := 0;
  quarantined_count_value integer := 0;
  quarantined_value jsonb := '[]'::jsonb;
  returned_state text;
  returned_message text;
  safe_error_code text;
  safe_external_id text;
  safe_fingerprint text;
  check_attempt_id uuid;
  check_checked_at timestamptz;
  check_expires_at timestamptz;
begin
  if auth.role() <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if provider_input not in ('polymarket', 'kalshi', 'tavily')
     or normalizer_version_input <> 'atinara-radar-v2'
     or eligibility_policy_version_input <> 'atinara-prediction-policy-v5'
     or jsonb_typeof(candidates_input) <> 'array'
     or jsonb_typeof(eligibility_checks_input) <> 'array'
     or jsonb_array_length(candidates_input) <> jsonb_array_length(eligibility_checks_input)
     or jsonb_array_length(candidates_input) > 240
     or octet_length(candidates_input::text) > 3145728 then
    raise exception 'INVALID_RADAR_ELIGIBILITY_BATCH' using errcode = '22023';
  end if;

  for item, item_ordinality in
    select value, ordinality
    from jsonb_array_elements(candidates_input) with ordinality
  loop
    check_item := eligibility_checks_input -> (item_ordinality::integer - 1);
    begin
      candidate := null;
      select * into candidate
      from private.external_market_candidates candidate_alias
      where candidate_alias.provider = provider_input
        and candidate_alias.external_id = item ->> 'external_id'
      for update;

      -- A conclusive terminal decision is monotonic. A later provider refresh
      -- may still report the contract as tradable, but it cannot make a public
      -- result unknown again. Reopening requires an explicit audited repair.
      if found
         and candidate.eligibility_status = 'terminal'
         and item ->> 'eligibility_status' is distinct from 'terminal'
         and jsonb_typeof(check_item) = 'object' then
        item := item || jsonb_build_object(
          'eligibility_status', 'terminal',
          'eligibility_reason_code', candidate.eligibility_reason_code,
          'eligibility_reason', candidate.eligibility_reason,
          'eligibility_evidence', candidate.eligibility_evidence,
          'eligibility_policy_version', 'atinara-prediction-policy-v5'
        );
        check_item := check_item || jsonb_build_object(
          'status', 'terminal',
          'reason_code', candidate.eligibility_reason_code,
          'reason', candidate.eligibility_reason,
          'evidence', candidate.eligibility_evidence,
          'decision_hash', encode(extensions.digest(convert_to(
            concat_ws('|', provider_input, candidate.external_id, 'terminal',
              coalesce(candidate.eligibility_reason_code, ''),
              coalesce(check_item ->> 'checked_at', '')),
            'UTF8'
          ), 'sha256'), 'hex')
        );
      end if;
      if item ->> 'provider' is distinct from provider_input
         or item ->> 'eligibility_policy_version' is distinct from 'atinara-prediction-policy-v5'
         or item ->> 'eligibility_status' not in (
           'eligible', 'terminal', 'inactive_option', 'technical_hold', 'invalid', 'duplicate'
         )
         or jsonb_typeof(check_item) <> 'object'
         or check_item ->> 'provider' is distinct from provider_input
         or check_item ->> 'external_id' is distinct from item ->> 'external_id'
         or check_item ->> 'policy_version' is distinct from 'atinara-prediction-policy-v5'
         or check_item ->> 'status' is distinct from item ->> 'eligibility_status'
         or coalesce(check_item ->> 'decision_hash', '') !~ '^[0-9a-f]{64}$'
         or jsonb_typeof(coalesce(check_item -> 'evidence', '[]'::jsonb)) <> 'array'
         or jsonb_array_length(coalesce(check_item -> 'evidence', '[]'::jsonb)) > 12 then
        raise exception 'INVALID_RADAR_ELIGIBILITY' using errcode = '22023';
      end if;
      begin
        check_attempt_id := (check_item ->> 'attempt_id')::uuid;
        check_checked_at := (check_item ->> 'checked_at')::timestamptz;
        check_expires_at := (check_item ->> 'expires_at')::timestamptz;
      exception when invalid_text_representation or datetime_field_overflow then
        raise exception 'INVALID_RADAR_ELIGIBILITY_DATE' using errcode = '22007';
      end;
      if check_expires_at <= check_checked_at then
        raise exception 'INVALID_RADAR_ELIGIBILITY_DATE' using errcode = '22007';
      end if;

      perform public.upsert_market_radar_batch_v2(
        provider_input,
        left(cache_key_input, 180),
        normalizer_version_input,
        jsonb_build_array(item),
        provider_status_input
      );

      select * into candidate
      from private.external_market_candidates candidate_alias
      where candidate_alias.provider = provider_input
        and candidate_alias.external_id = item ->> 'external_id'
      for update;
      if not found then
        raise exception 'RADAR_ROW_PERSISTENCE_INCOMPLETE' using errcode = 'P0001';
      end if;

      insert into private.market_radar_eligibility_checks (
        attempt_id, candidate_id, provider, external_id, event_group_key,
        policy_version, status, reason_code, reason, evidence,
        checked_at, expires_at, decision_hash
      ) values (
        check_attempt_id,
        candidate.id,
        provider_input,
        candidate.external_id,
        nullif(left(check_item ->> 'event_group_key', 240), ''),
        'atinara-prediction-policy-v5',
        check_item ->> 'status',
        nullif(left(check_item ->> 'reason_code', 100), ''),
        nullif(left(check_item ->> 'reason', 1000), ''),
        coalesce(check_item -> 'evidence', '[]'::jsonb),
        check_checked_at,
        check_expires_at,
        lower(check_item ->> 'decision_hash')
      )
      on conflict (attempt_id) do nothing;

      select * into check_row
      from private.market_radar_eligibility_checks check_alias
      where check_alias.attempt_id = check_attempt_id;
      if not found
         or check_row.candidate_id is distinct from candidate.id
         or check_row.decision_hash is distinct from lower(check_item ->> 'decision_hash') then
        raise exception 'RADAR_ELIGIBILITY_IDEMPOTENCY_CONFLICT' using errcode = '40001';
      end if;

      update private.external_market_candidates candidate_alias set
        current_eligibility_check_id = check_row.id,
        eligibility_status = check_row.status,
        eligibility_reason_code = check_row.reason_code,
        eligibility_reason = check_row.reason,
        eligibility_evidence = check_row.evidence,
        eligibility_checked_at = check_row.checked_at,
        eligibility_expires_at = check_row.expires_at,
        eligibility_policy_version = check_row.policy_version,
        updated_at = now()
      where candidate_alias.id = candidate.id;
      accepted_count_value := accepted_count_value + 1;
    exception when others then
      get stacked diagnostics
        returned_state = returned_sqlstate,
        returned_message = message_text;
      if returned_state = '57014'
         or not (
           returned_message in (
             'INVALID_RADAR_CANDIDATE',
             'INCOMPLETE_RADAR_VERIFICATION',
             'RADAR_BATCH_TOO_LARGE',
             'INVALID_RADAR_ELIGIBILITY',
             'INVALID_RADAR_ELIGIBILITY_DATE'
           )
           or returned_state in (
             '22001', '22003', '22007', '22008', '22P02',
             '23502', '23503', '23514'
           )
         ) then
        raise;
      end if;
      safe_error_code := case when returned_message in (
        'INVALID_RADAR_CANDIDATE', 'INCOMPLETE_RADAR_VERIFICATION',
        'RADAR_BATCH_TOO_LARGE', 'INVALID_RADAR_ELIGIBILITY',
        'INVALID_RADAR_ELIGIBILITY_DATE'
      ) then returned_message else 'RADAR_CANDIDATE_DATA_INVALID' end;
      safe_external_id := coalesce(nullif(left(item ->> 'external_id', 220), ''), '[sin-identificador]');
      safe_fingerprint := case when coalesce(item ->> 'fingerprint', '') ~ '^[0-9a-fA-F]{64}$'
        then lower(item ->> 'fingerprint') else null end;
      insert into private.market_radar_candidate_quarantines(
        provider, cache_key, external_id, fingerprint, stage,
        error_code, database_code, operation
      ) values (
        provider_input, left(cache_key_input, 180), safe_external_id,
        safe_fingerprint, 'eligibility_persistence', safe_error_code,
        returned_state, 'upsert_market_radar_batch_with_eligibility_v1'
      );
      quarantined_count_value := quarantined_count_value + 1;
      quarantined_value := quarantined_value || jsonb_build_array(jsonb_build_object(
        'provider', provider_input,
        'external_id', safe_external_id,
        'fingerprint', safe_fingerprint,
        'stage', 'eligibility_persistence',
        'code', safe_error_code,
        'database_code', returned_state,
        'operation', 'upsert_market_radar_batch_with_eligibility_v1'
      ));
    end;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'upserted', accepted_count_value,
    'accepted_count', accepted_count_value,
    'eligibility_checks_linked', accepted_count_value,
    'quarantined_count', quarantined_count_value,
    'quarantined', quarantined_value,
    'row_isolation', 'database_subtransaction_v1',
    'atomic_per_candidate', true
  );
end;
$function$;

revoke all on function public.upsert_market_radar_batch_with_eligibility_v1(
  text,text,text,jsonb,jsonb,text,jsonb
) from public, anon, authenticated;
grant execute on function public.upsert_market_radar_batch_with_eligibility_v1(
  text,text,text,jsonb,jsonb,text,jsonb
) to service_role;

create or replace function private.market_radar_candidate_resolution_source_ready_v1(
  candidate_input private.external_market_candidates
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select coalesce(candidate_input.normalized_payload ->> 'atinara_resolution_source_url', '') <> ''
    and exists (
      select 1
      from jsonb_array_elements(coalesce(candidate_input.eligibility_evidence, '[]'::jsonb)) evidence_item
      where evidence_item ->> 'url' = candidate_input.normalized_payload ->> 'atinara_resolution_source_url'
        and evidence_item ->> 'source_type' = 'official'
        and evidence_item ->> 'retrieval_status' = 'verified_content'
        and evidence_item ->> 'evidence_basis' = 'retrieved_content'
        and evidence_item ->> 'parser_version' = 'atinara-official-content-v1'
        and evidence_item ->> 'claim_status' = 'direct'
        and coalesce((evidence_item ->> 'direct_claim')::boolean, false)
        and coalesce((evidence_item ->> 'claim_verifiable')::boolean, false)
        and coalesce(evidence_item ->> 'content_sha256', '') ~ '^[0-9a-f]{64}$'
    )
    and exists (
      select 1
      from private.market_source_registry registry
      where private.market_primary_registry_row_matches_v1(
        registry,
        candidate_input.normalized_payload ->> 'atinara_resolution_source_url',
        candidate_input.normalized_payload ->> 'atinara_category'
      )
    );
$function$;

revoke all on function private.market_radar_candidate_resolution_source_ready_v1(
  private.external_market_candidates
) from public, anon, authenticated, service_role;

create or replace function public.list_market_radar_candidates_v2(
  provider_filter text default null,
  category_filter text default null,
  quality_filter text default null,
  query_filter text default null,
  order_key text default 'recommended',
  horizon_filter text default '180d',
  limit_count integer default 240,
  offset_count integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  result jsonb;
  checked_at_value timestamptz := now();
begin
  perform private.require_current_admin();
  if provider_filter is not null and provider_filter <> ''
     and provider_filter not in ('polymarket', 'kalshi', 'tavily') then
    raise exception 'INVALID_RADAR_PROVIDER' using errcode = '22023';
  end if;
  if order_key not in ('recommended', 'popularity', 'closing', 'recent') then
    raise exception 'INVALID_RADAR_ORDER' using errcode = '22023';
  end if;
  if quality_filter is not null and quality_filter <> ''
     and quality_filter not in ('fit', 'review', 'rejected', 'all') then
    raise exception 'INVALID_RADAR_QUALITY' using errcode = '22023';
  end if;
  if horizon_filter not in ('30d', '90d', '180d', '365d') then
    raise exception 'INVALID_RADAR_HORIZON' using errcode = '22023';
  end if;

  select coalesce(jsonb_agg(private.market_radar_eligibility_payload(candidate_row)), '[]'::jsonb)
  into result
  from (
    select candidate.*
    from private.external_market_candidates candidate
    join private.market_radar_eligibility_checks eligibility
      on eligibility.id = candidate.current_eligibility_check_id
     and eligibility.candidate_id = candidate.id
    where candidate.normalizer_version = 'atinara-radar-v2'
      and candidate.family_version = 'atinara-market-family-v4'
      and candidate.family_key is not null
      and candidate.family_child_key is not null
      and candidate.state = 'available'
      and candidate.verification_status = 'verified_open'
      and candidate.quality_status <> 'rejected'
      and candidate.eligibility_policy_version = 'atinara-prediction-policy-v5'
      and candidate.eligibility_status = 'eligible'
      and eligibility.policy_version = candidate.eligibility_policy_version
      and eligibility.status = candidate.eligibility_status
      and eligibility.checked_at = candidate.eligibility_checked_at
      and eligibility.expires_at = candidate.eligibility_expires_at
      and eligibility.expires_at > checked_at_value
      and not exists (
        select 1 from public.markets market_alias
        where market_alias.family_key = candidate.family_key
          and market_alias.family_child_key = candidate.family_child_key
      )
      and not exists (
        select 1 from private.market_drafts draft_alias
        where (
          draft_alias.radar_candidate_id = candidate.id
          or (
            draft_alias.family_key = candidate.family_key
            and draft_alias.family_child_key = candidate.family_child_key
          )
        )
        and draft_alias.workflow_status not in ('cancelled', 'annulled')
      )
      and (
        coalesce(
          nullif(candidate.normalized_payload ->> 'source_close_at', '')::timestamptz,
          nullif(candidate.normalized_payload ->> 'atinara_closes_at', '')::timestamptz
        ) is null
        or coalesce(
          nullif(candidate.normalized_payload ->> 'source_close_at', '')::timestamptz,
          nullif(candidate.normalized_payload ->> 'atinara_closes_at', '')::timestamptz
        ) <= checked_at_value + case horizon_filter
          when '30d' then interval '30 days'
          when '90d' then interval '90 days'
          when '365d' then interval '365 days'
          else interval '180 days'
        end
      )
      and (provider_filter is null or provider_filter = '' or candidate.provider = provider_filter)
      and (category_filter is null or category_filter = '' or candidate.atinara_category = category_filter)
      and (quality_filter is null or quality_filter in ('', 'all', 'review', 'fit'))
      and (
        query_filter is null or query_filter = ''
        or candidate.normalized_payload ->> 'source_title' ilike '%' || query_filter || '%'
        or candidate.normalized_payload ->> 'source_question' ilike '%' || query_filter || '%'
        or candidate.normalized_payload ->> 'atinara_question' ilike '%' || query_filter || '%'
      )
    order by
      case when order_key = 'recommended' then candidate.quality_score end desc nulls last,
      case when order_key = 'popularity' then coalesce((candidate.normalized_payload ->> 'source_volume_total')::numeric, 0) end desc nulls last,
      case when order_key = 'closing' then nullif(candidate.normalized_payload ->> 'source_close_at', '')::timestamptz end asc nulls last,
      case when order_key = 'recent' then coalesce(candidate.source_updated_at, candidate.fetched_at) end desc nulls last,
      candidate.quality_score desc,
      candidate.fetched_at desc
    limit least(greatest(coalesce(limit_count, 240), 1), 500)
    offset greatest(coalesce(offset_count, 0), 0)
  ) candidate_row;
  return result;
end;
$function$;

revoke all on function public.list_market_radar_candidates_v2(
  text,text,text,text,text,text,integer,integer
) from public, anon, authenticated;
grant execute on function public.list_market_radar_candidates_v2(
  text,text,text,text,text,text,integer,integer
) to authenticated;

create or replace function public.get_market_radar_candidate(candidate_id_input uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
begin
  perform private.require_current_admin();
  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input;
  if not found then
    raise exception 'RADAR_CANDIDATE_NOT_FOUND' using errcode = 'P0001';
  end if;
  return private.market_radar_eligibility_payload(candidate);
end;
$function$;

revoke all on function public.get_market_radar_candidate(uuid)
  from public, anon, authenticated;
grant execute on function public.get_market_radar_candidate(uuid)
  to authenticated;

create or replace function public.get_market_radar_candidate_for_revalidation_v1(
  candidate_id_input uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input;
  if not found then
    raise exception 'RADAR_CANDIDATE_NOT_FOUND' using errcode = 'P0001';
  end if;
  return private.market_radar_eligibility_payload(candidate);
end;
$function$;

revoke all on function public.get_market_radar_candidate_for_revalidation_v1(uuid)
  from public, anon, authenticated;
grant execute on function public.get_market_radar_candidate_for_revalidation_v1(uuid)
  to service_role;

create or replace function public.apply_market_radar_prepare_eligibility_v1(
  candidate_id_input uuid,
  expected_preparation_revision_input bigint,
  normalizer_version_input text,
  eligibility_checked_at_input timestamptz,
  eligibility_input jsonb,
  eligibility_check_input jsonb,
  reserve_for_prepare_input boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
  check_row private.market_radar_eligibility_checks%rowtype;
  check_attempt_id uuid;
  check_expires_at timestamptz;
  check_status text;
  safe_payload jsonb;
begin
  if auth.role() <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if normalizer_version_input <> 'atinara-radar-v2'
     or jsonb_typeof(eligibility_input) <> 'object'
     or jsonb_typeof(eligibility_check_input) <> 'object'
     or eligibility_input ->> 'eligibility_policy_version' is distinct from 'atinara-prediction-policy-v5'
     or eligibility_check_input ->> 'policy_version' is distinct from 'atinara-prediction-policy-v5'
     or eligibility_input ->> 'eligibility_status' is distinct from eligibility_check_input ->> 'status'
     or coalesce(eligibility_check_input ->> 'decision_hash', '') !~ '^[0-9a-f]{64}$' then
    raise exception 'INVALID_RADAR_ELIGIBILITY' using errcode = '22023';
  end if;
  begin
    check_attempt_id := (eligibility_check_input ->> 'attempt_id')::uuid;
    check_expires_at := (eligibility_check_input ->> 'expires_at')::timestamptz;
  exception when invalid_text_representation or datetime_field_overflow then
    raise exception 'INVALID_RADAR_ELIGIBILITY_DATE' using errcode = '22007';
  end;
  check_status := eligibility_check_input ->> 'status';
  if check_status not in ('eligible', 'terminal', 'inactive_option', 'technical_hold', 'invalid', 'duplicate')
     or check_expires_at <= eligibility_checked_at_input
     or jsonb_typeof(coalesce(eligibility_check_input -> 'evidence', '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(eligibility_check_input -> 'evidence', '[]'::jsonb)) > 12 then
    raise exception 'INVALID_RADAR_ELIGIBILITY' using errcode = '22023';
  end if;

  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input
  for update;
  if not found then raise exception 'RADAR_CANDIDATE_NOT_FOUND' using errcode = 'P0001'; end if;
  if candidate.preparation_revision is distinct from expected_preparation_revision_input then
    raise exception 'PREPARATION_REVISION_MISMATCH' using errcode = '40001';
  end if;
  if eligibility_input ->> 'provider' is distinct from candidate.provider
     or eligibility_input ->> 'external_id' is distinct from candidate.external_id
     or eligibility_check_input ->> 'provider' is distinct from candidate.provider
     or eligibility_check_input ->> 'external_id' is distinct from candidate.external_id then
    raise exception 'RADAR_ELIGIBILITY_IDENTITY_MISMATCH' using errcode = '40001';
  end if;

  -- Una resolución terminal ya vinculada es monotónica también frente a una
  -- comprobación concurrente iniciada cuando la candidata aún parecía abierta.
  -- Solo una reparación administrativa auditada (fuera de esta RPC) podría
  -- reconsiderarla; ni un reintento ni el estado abierto del proveedor lo hacen.
  if candidate.eligibility_status = 'terminal' and check_status <> 'terminal' then
    check_status := 'terminal';
    eligibility_input := eligibility_input || jsonb_build_object(
      'eligibility_status', 'terminal',
      'eligibility_reason_code', candidate.eligibility_reason_code,
      'eligibility_reason', candidate.eligibility_reason,
      'eligibility_evidence', candidate.eligibility_evidence,
      'eligibility_policy_version', 'atinara-prediction-policy-v5'
    );
    eligibility_check_input := eligibility_check_input || jsonb_build_object(
      'status', 'terminal',
      'reason_code', candidate.eligibility_reason_code,
      'reason', candidate.eligibility_reason,
      'evidence', candidate.eligibility_evidence,
      'decision_hash', encode(extensions.digest(convert_to(
        concat_ws('|', candidate.provider, candidate.external_id, 'terminal',
          coalesce(candidate.eligibility_reason_code, ''), eligibility_checked_at_input::text),
        'UTF8'
      ), 'sha256'), 'hex')
    );
  end if;

  -- A retry with the same attempt is a read of the current authoritative
  -- outcome, never a second material write. The candidate row is already
  -- locked, so concurrent double-clicks serialize here after the first
  -- transaction commits. Apply the terminal-monotonic transform first so an
  -- originally-open request replays against the exact persisted terminal hash.
  select * into check_row
  from private.market_radar_eligibility_checks check_alias
  where check_alias.attempt_id = check_attempt_id;
  if found then
    if check_row.candidate_id is distinct from candidate.id
       or check_row.decision_hash is distinct from lower(eligibility_check_input ->> 'decision_hash') then
      raise exception 'RADAR_ELIGIBILITY_IDEMPOTENCY_CONFLICT' using errcode = '40001';
    end if;
    safe_payload := private.market_radar_eligibility_payload(candidate);
    if candidate.eligibility_status <> 'eligible' then
      return jsonb_build_object(
        'ok', false,
        'error', case when candidate.eligibility_status = 'terminal'
          then 'RADAR_CANDIDATE_RESOLVED'
          when candidate.eligibility_status = 'duplicate'
          then 'RADAR_CONFIRMED_DUPLICATE'
          else coalesce(candidate.eligibility_reason_code, 'RADAR_CANDIDATE_INELIGIBLE') end,
        'candidate', safe_payload,
        'persisted', true,
        'idempotent', true,
        'reservation', jsonb_build_object('preparation_revision', candidate.preparation_revision)
      );
    end if;
    if reserve_for_prepare_input and candidate.state <> 'available' then
      raise exception 'CANDIDATE_NOT_PREPARABLE' using errcode = '40001';
    end if;
    return jsonb_build_object(
      'ok', true,
      'candidate', safe_payload,
      'eligibility_check_id', candidate.current_eligibility_check_id,
      'idempotent', true,
      'reservation', jsonb_build_object(
        'preparation_revision', candidate.preparation_revision,
        'idempotent', true
      )
    );
  end if;

  insert into private.market_radar_eligibility_checks (
    attempt_id, candidate_id, provider, external_id, event_group_key,
    policy_version, status, reason_code, reason, evidence,
    checked_at, expires_at, decision_hash
  ) values (
    check_attempt_id,
    candidate.id,
    candidate.provider,
    candidate.external_id,
    candidate.event_group_key,
    'atinara-prediction-policy-v5',
    check_status,
    nullif(left(eligibility_check_input ->> 'reason_code', 100), ''),
    nullif(left(eligibility_check_input ->> 'reason', 1000), ''),
    coalesce(eligibility_check_input -> 'evidence', '[]'::jsonb),
    eligibility_checked_at_input,
    check_expires_at,
    lower(eligibility_check_input ->> 'decision_hash')
  ) on conflict (attempt_id) do nothing;

  select * into check_row
  from private.market_radar_eligibility_checks check_alias
  where check_alias.attempt_id = check_attempt_id;
  if not found
     or check_row.candidate_id is distinct from candidate.id
     or check_row.decision_hash is distinct from lower(eligibility_check_input ->> 'decision_hash') then
    raise exception 'RADAR_ELIGIBILITY_IDEMPOTENCY_CONFLICT' using errcode = '40001';
  end if;

  update private.external_market_candidates candidate_alias set
    normalized_payload = (
      candidate_alias.normalized_payload
      - 'atinara_resolution_source_url'
      - 'resolution_source_evidence'
    ) || jsonb_strip_nulls(jsonb_build_object(
      'atinara_question', eligibility_input ->> 'atinara_question',
      'atinara_category', eligibility_input ->> 'atinara_category',
      'atinara_resolution_criteria', eligibility_input ->> 'atinara_resolution_criteria',
      'atinara_resolution_source_url', eligibility_input ->> 'atinara_resolution_source_url',
      'resolution_source_evidence', coalesce(eligibility_input -> 'resolution_source_evidence', '[]'::jsonb),
      'eligibility_status', check_row.status,
      'eligibility_reason_code', check_row.reason_code,
      'eligibility_reason', check_row.reason,
      'eligibility_checked_at', check_row.checked_at,
      'eligibility_expires_at', check_row.expires_at,
      'eligibility_policy_version', check_row.policy_version,
      'eligibility_evidence', check_row.evidence
    )),
    current_eligibility_check_id = check_row.id,
    eligibility_status = check_row.status,
    eligibility_reason_code = check_row.reason_code,
    eligibility_reason = check_row.reason,
    eligibility_evidence = check_row.evidence,
    eligibility_checked_at = check_row.checked_at,
    eligibility_expires_at = check_row.expires_at,
    eligibility_policy_version = check_row.policy_version,
    updated_at = now()
  where candidate_alias.id = candidate.id;

  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input;
  safe_payload := private.market_radar_eligibility_payload(candidate);
  if candidate.eligibility_status <> 'eligible' then
    return jsonb_build_object(
      'ok', false,
      'error', case when candidate.eligibility_status = 'terminal'
        then 'RADAR_CANDIDATE_RESOLVED'
        when candidate.eligibility_status = 'duplicate'
        then 'RADAR_CONFIRMED_DUPLICATE'
        else coalesce(candidate.eligibility_reason_code, 'RADAR_CANDIDATE_INELIGIBLE') end,
      'candidate', safe_payload,
      'persisted', true,
      'reservation', jsonb_build_object('preparation_revision', candidate.preparation_revision)
    );
  end if;
  if reserve_for_prepare_input and candidate.state <> 'available' then
    raise exception 'CANDIDATE_NOT_PREPARABLE' using errcode = '40001';
  end if;
  return jsonb_build_object(
    'ok', true,
    'candidate', safe_payload,
    'eligibility_check_id', check_row.id,
    'reservation', jsonb_build_object(
      'preparation_revision', candidate.preparation_revision,
      'idempotent', true
    )
  );
end;
$function$;

revoke all on function public.apply_market_radar_prepare_eligibility_v1(
  uuid,bigint,text,timestamptz,jsonb,jsonb,boolean
) from public, anon, authenticated;
grant execute on function public.apply_market_radar_prepare_eligibility_v1(
  uuid,bigint,text,timestamptz,jsonb,jsonb,boolean
) to service_role;

create or replace function private.assert_market_radar_candidate_eligible_v1(
  candidate_id_input uuid,
  expected_preparation_revision_input bigint default null
)
returns private.external_market_candidates
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
  eligibility private.market_radar_eligibility_checks%rowtype;
begin
  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = candidate_id_input
  for share;
  if not found then raise exception 'RADAR_CANDIDATE_NOT_FOUND' using errcode = 'P0001'; end if;
  if expected_preparation_revision_input is not null
     and candidate.preparation_revision is distinct from expected_preparation_revision_input then
    raise exception 'RADAR_PREPARATION_REVISION_MISMATCH' using errcode = '40001';
  end if;
  select * into eligibility
  from private.market_radar_eligibility_checks check_alias
  where check_alias.id = candidate.current_eligibility_check_id;
  if not found
     or eligibility.candidate_id is distinct from candidate.id
     or eligibility.policy_version is distinct from 'atinara-prediction-policy-v5'
     or eligibility.status is distinct from candidate.eligibility_status
     or eligibility.checked_at is distinct from candidate.eligibility_checked_at
     or eligibility.expires_at is distinct from candidate.eligibility_expires_at then
    raise exception 'RADAR_ELIGIBILITY_REQUIRED' using errcode = '55000';
  end if;
  if candidate.eligibility_status = 'terminal'
     or candidate.verification_status = 'rejected_resolved' then
    raise exception 'RADAR_EVENT_ALREADY_RESOLVED' using errcode = '55000';
  end if;
  if candidate.eligibility_status = 'duplicate'
     or candidate.verification_status = 'rejected_duplicate' then
    raise exception 'RADAR_CONFIRMED_DUPLICATE' using errcode = '23505';
  end if;
  if candidate.eligibility_status is distinct from 'eligible'
     or candidate.eligibility_policy_version is distinct from 'atinara-prediction-policy-v5'
     or candidate.verification_status is distinct from 'verified_open' then
    raise exception 'RADAR_CANDIDATE_INELIGIBLE' using errcode = '55000';
  end if;
  if not private.market_radar_candidate_resolution_source_ready_v1(candidate) then
    raise exception 'RADAR_RESOLUTION_SOURCE_REQUIRED' using errcode = '55000';
  end if;
  if eligibility.expires_at <= clock_timestamp() then
    raise exception 'RADAR_ELIGIBILITY_EXPIRED' using errcode = '55000';
  end if;
  return candidate;
end;
$function$;

revoke all on function private.assert_market_radar_candidate_eligible_v1(uuid,bigint)
  from public, anon, authenticated, service_role;

create or replace function public.save_market_draft_from_radar(
  candidate_id_input uuid,
  draft_id_input uuid,
  expected_version_input bigint,
  draft_input jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id_value uuid := private.require_current_admin();
  candidate private.external_market_candidates%rowtype;
  eligibility private.market_radar_eligibility_checks%rowtype;
  submitted_revision bigint;
  save_result jsonb;
  saved_draft_id uuid;
begin
  if jsonb_typeof(draft_input) <> 'object'
     or coalesce(draft_input ->> '_radar_preparation_revision', '') !~ '^[1-9][0-9]*$' then
    raise exception 'RADAR_PREPARATION_REVISION_MISMATCH' using errcode = '40001';
  end if;
  submitted_revision := (draft_input ->> '_radar_preparation_revision')::bigint;
  candidate := private.assert_market_radar_candidate_eligible_v1(
    candidate_id_input, submitted_revision
  );
  if candidate.state not in ('available', 'prepared') then
    raise exception 'RADAR_CANDIDATE_NOT_PREPARABLE' using errcode = '55000';
  end if;
  if candidate.state = 'available'
     and exists (
       select 1 from jsonb_array_elements(coalesce(candidate.duplicate_matches, '[]'::jsonb)) match
       where coalesce((match ->> 'blocking')::boolean, true)
         and match ->> 'relationship' in ('exact_duplicate', 'semantic_duplicate')
     ) then
    raise exception 'RADAR_CONFIRMED_DUPLICATE' using errcode = '23505';
  end if;
  select * into eligibility
  from private.market_radar_eligibility_checks
  where id = candidate.current_eligibility_check_id;

  save_result := public.save_market_draft_from_radar_without_authoritative_fact_gate_v1(
    candidate_id_input,
    draft_id_input,
    expected_version_input,
    draft_input - '_radar_fact_check_id' - '_radar_eligibility_check_id'
  );
  saved_draft_id := nullif(save_result #>> '{draft,id}', '')::uuid;
  if saved_draft_id is not null then
    update private.market_drafts draft_alias set
      source_provenance = coalesce(draft_alias.source_provenance, '{}'::jsonb) || jsonb_build_object(
        'radar_candidate_id', candidate.id,
        'radar_preparation_revision', candidate.preparation_revision,
        'radar_eligibility_check_id', eligibility.id,
        'radar_eligibility_policy_version', eligibility.policy_version,
        'radar_eligibility_status', eligibility.status,
        'radar_eligibility_checked_at', eligibility.checked_at,
        'radar_eligibility_decision_hash', eligibility.decision_hash,
        'atomic_eligibility_gate', true
      )
    where draft_alias.id = saved_draft_id;
  end if;
  return save_result || jsonb_build_object(
    'radar_eligibility_check_id', eligibility.id,
    'radar_eligibility_policy_version', eligibility.policy_version,
    'atomic_eligibility_gate', true
  );
end;
$function$;

revoke all on function public.save_market_draft_from_radar(uuid,uuid,bigint,jsonb)
  from public, anon, authenticated;
grant execute on function public.save_market_draft_from_radar(uuid,uuid,bigint,jsonb)
  to authenticated;

create or replace function public.save_market_draft_from_radar_intelligence(
  candidate_id_input uuid,
  draft_id_input uuid,
  expected_version_input bigint,
  draft_input jsonb,
  expert_run_id_input uuid,
  contract_input jsonb,
  sources_input jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  actor_id_value uuid := private.require_current_admin();
  candidate private.external_market_candidates%rowtype;
  eligibility private.market_radar_eligibility_checks%rowtype;
  submitted_revision bigint;
  save_result jsonb;
  saved_draft_id uuid;
begin
  if jsonb_typeof(draft_input) <> 'object'
     or coalesce(draft_input ->> '_radar_preparation_revision', '') !~ '^[1-9][0-9]*$' then
    raise exception 'RADAR_PREPARATION_REVISION_MISMATCH' using errcode = '40001';
  end if;
  submitted_revision := (draft_input ->> '_radar_preparation_revision')::bigint;
  candidate := private.assert_market_radar_candidate_eligible_v1(
    candidate_id_input, submitted_revision
  );
  select * into eligibility
  from private.market_radar_eligibility_checks
  where id = candidate.current_eligibility_check_id;

  save_result := public.save_market_draft_from_radar_intelligence_without_authoritative_fact_gate_v1(
    candidate_id_input,
    draft_id_input,
    expected_version_input,
    draft_input - '_radar_fact_check_id' - '_radar_eligibility_check_id',
    expert_run_id_input,
    contract_input,
    sources_input
  );
  saved_draft_id := nullif(save_result #>> '{draft,id}', '')::uuid;
  if saved_draft_id is not null then
    update private.market_drafts draft_alias set
      source_provenance = coalesce(draft_alias.source_provenance, '{}'::jsonb) || jsonb_build_object(
        'radar_candidate_id', candidate.id,
        'radar_preparation_revision', candidate.preparation_revision,
        'radar_eligibility_check_id', eligibility.id,
        'radar_eligibility_policy_version', eligibility.policy_version,
        'radar_eligibility_status', eligibility.status,
        'radar_eligibility_checked_at', eligibility.checked_at,
        'radar_eligibility_decision_hash', eligibility.decision_hash,
        'market_expert_run_id', expert_run_id_input,
        'atomic_eligibility_gate', true
      )
    where draft_alias.id = saved_draft_id;
  end if;
  return save_result || jsonb_build_object(
    'radar_eligibility_check_id', eligibility.id,
    'radar_eligibility_policy_version', eligibility.policy_version,
    'atomic_eligibility_gate', true
  );
end;
$function$;

revoke all on function public.save_market_draft_from_radar_intelligence(
  uuid,uuid,bigint,jsonb,uuid,jsonb,jsonb
) from public, anon, authenticated;
grant execute on function public.save_market_draft_from_radar_intelligence(
  uuid,uuid,bigint,jsonb,uuid,jsonb,jsonb
) to authenticated;

create or replace function public.get_market_intelligence_origin(
  origin_type_input text,
  origin_id_input text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  result jsonb;
  candidate private.external_market_candidates%rowtype;
  eligibility private.market_radar_eligibility_checks%rowtype;
  can_prepare boolean := false;
  blocked_code text;
begin
  if auth.role() <> 'service_role' then
    perform private.require_current_admin();
  end if;

  if origin_type_input = 'observatory_signal' then
    select to_jsonb(signal) || jsonb_build_object(
      'watch_entity_id', (
        select entity.id
        from private.data_observatory_entities entity
        where entity.provider = signal.provider
          and entity.external_id = signal.entity_id
          and entity.active
        order by entity.updated_at desc
        limit 1
      ),
      'recent_context', coalesce((
        select jsonb_agg(to_jsonb(context_row) order by context_row.observed_at desc)
        from (
          select * from private.data_observatory_context_items
          where origin_type = 'observatory_signal'
            and origin_id = origin_id_input
            and active
          order by observed_at desc
          limit 10
        ) context_row
      ), '[]'::jsonb)
    ) into result
    from private.data_observatory_signals signal
    where signal.id::text = origin_id_input;
  elsif origin_type_input = 'radar_candidate' then
    select * into candidate
    from private.external_market_candidates candidate_alias
    where candidate_alias.id::text = origin_id_input;
    if candidate.id is not null then
      select * into eligibility
      from private.market_radar_eligibility_checks check_alias
      where check_alias.id = candidate.current_eligibility_check_id;
      can_prepare := (candidate.state in ('available', 'prepared')
        and candidate.verification_status = 'verified_open'
        and candidate.eligibility_status = 'eligible'
        and candidate.eligibility_policy_version = 'atinara-prediction-policy-v5'
        and eligibility.id is not null
        and eligibility.candidate_id = candidate.id
        and eligibility.status = 'eligible'
        and eligibility.policy_version = 'atinara-prediction-policy-v5'
        and eligibility.expires_at > now()
        and private.market_radar_candidate_resolution_source_ready_v1(candidate));
      blocked_code := case
        when can_prepare then null
        when candidate.eligibility_status = 'terminal'
          or candidate.verification_status = 'rejected_resolved'
          then 'EVENT_ALREADY_RESOLVED'
        when candidate.eligibility_status = 'duplicate'
          or candidate.verification_status = 'rejected_duplicate'
          then 'DUPLICATE_MARKET'
        when candidate.eligibility_policy_version is distinct from 'atinara-prediction-policy-v5'
          then 'RADAR_ELIGIBILITY_POLICY_OUTDATED'
        when candidate.eligibility_status = 'eligible'
          and not private.market_radar_candidate_resolution_source_ready_v1(candidate)
          then 'RADAR_RESOLUTION_SOURCE_REQUIRED'
        when candidate.state not in ('available', 'prepared')
          then 'RADAR_CANDIDATE_NOT_PREPARABLE'
        else 'RADAR_ELIGIBILITY_REQUIRED'
      end;
      result := private.market_radar_eligibility_payload(candidate) || jsonb_build_object(
        'advancement_gate', jsonb_build_object(
          'can_analyze', true,
          'can_prepare', can_prepare,
          'blocked_code', blocked_code,
          'retryable', blocked_code in ('RADAR_ELIGIBILITY_REQUIRED', 'RADAR_RESOLUTION_SOURCE_REQUIRED'),
          'eligibility_check_id', eligibility.id,
          'eligibility_status', eligibility.status
        )
      );
    end if;
  elsif origin_type_input = 'context_story_arc' then
    select to_jsonb(arc) into result
    from private.data_observatory_story_arcs arc
    where arc.id::text = origin_id_input;
  else
    raise exception 'INTELLIGENCE_ORIGIN_INVALID' using errcode = '22023';
  end if;
  if result is null then
    raise exception 'INTELLIGENCE_ORIGIN_NOT_FOUND' using errcode = 'P0001';
  end if;
  return result;
end;
$function$;

revoke all on function public.get_market_intelligence_origin(text,text)
  from public, anon, authenticated;
grant execute on function public.get_market_intelligence_origin(text,text)
  to authenticated, service_role;

create or replace function private.assert_market_radar_draft_eligibility_v1(
  draft_input private.market_drafts,
  checked_at_input timestamptz default clock_timestamp()
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  candidate private.external_market_candidates%rowtype;
  eligibility private.market_radar_eligibility_checks%rowtype;
  provenance jsonb := coalesce(draft_input.source_provenance, '{}'::jsonb);
  provenance_check_id bigint;
  provenance_revision bigint;
begin
  if draft_input.radar_candidate_id is null
     and not (provenance ? 'radar_candidate_id')
     and not (provenance ? 'radar_eligibility_check_id')
     and not (provenance ? 'radar_fact_check_id') then
    return;
  end if;
  if draft_input.radar_candidate_id is null then
    raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
  end if;
  select * into candidate
  from private.external_market_candidates candidate_alias
  where candidate_alias.id = draft_input.radar_candidate_id
  for share;
  if not found then
    raise exception 'RADAR_ELIGIBILITY_REQUIRED' using errcode = '55000';
  end if;
  if checked_at_input is null
     or checked_at_input > clock_timestamp() + interval '1 minute' then
    raise exception 'RADAR_ELIGIBILITY_CHECK_TIME_INVALID' using errcode = '22007';
  end if;
  if coalesce(provenance ->> 'radar_preparation_revision', '') !~ '^[1-9][0-9]*$' then
    raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
  end if;
  begin
    provenance_revision := (provenance ->> 'radar_preparation_revision')::bigint;
  exception when invalid_text_representation or numeric_value_out_of_range then
    raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
  end;
  -- A renewed check may rotate from A to B while the material projection stays
  -- at R. Any material refresh to R+1 invalidates the draft and its review.
  perform private.assert_market_radar_candidate_eligible_v1(
    candidate.id, provenance_revision
  );

  if provenance ? 'radar_eligibility_check_id' then
    begin
      provenance_check_id := (provenance ->> 'radar_eligibility_check_id')::bigint;
    exception when invalid_text_representation or numeric_value_out_of_range then
      raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
    end;
    select * into eligibility
    from private.market_radar_eligibility_checks check_alias
    where check_alias.id = provenance_check_id;
    if not found
       or eligibility.candidate_id is distinct from candidate.id
       or eligibility.policy_version is distinct from provenance ->> 'radar_eligibility_policy_version'
       or eligibility.status is distinct from 'eligible'
       or eligibility.decision_hash is distinct from provenance ->> 'radar_eligibility_decision_hash' then
      raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
    end if;
  elsif not (provenance ? 'radar_fact_check_id') then
    -- Only historical Radar drafts may use the legacy append-only provenance.
    raise exception 'RADAR_DRAFT_ELIGIBILITY_PROVENANCE_REQUIRED' using errcode = '55000';
  end if;
end;
$function$;

revoke all on function private.assert_market_radar_draft_eligibility_v1(
  private.market_drafts,timestamptz
) from public, anon, authenticated, service_role;

create or replace function private.market_draft_radar_eligibility_gate_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  old_link jsonb := jsonb_build_object(
    'candidate', old.source_provenance -> 'radar_candidate_id',
    'revision', old.source_provenance -> 'radar_preparation_revision',
    'check', old.source_provenance -> 'radar_eligibility_check_id',
    'policy', old.source_provenance -> 'radar_eligibility_policy_version',
    'status', old.source_provenance -> 'radar_eligibility_status',
    'hash', old.source_provenance -> 'radar_eligibility_decision_hash'
  );
  new_link jsonb := jsonb_build_object(
    'candidate', new.source_provenance -> 'radar_candidate_id',
    'revision', new.source_provenance -> 'radar_preparation_revision',
    'check', new.source_provenance -> 'radar_eligibility_check_id',
    'policy', new.source_provenance -> 'radar_eligibility_policy_version',
    'status', new.source_provenance -> 'radar_eligibility_status',
    'hash', new.source_provenance -> 'radar_eligibility_decision_hash'
  );
  old_radar_linked boolean := old.radar_candidate_id is not null
    or coalesce(old.source_provenance, '{}'::jsonb) ? 'radar_candidate_id';
  initial_link boolean := false;
  safe_rebind boolean := false;
begin
  if old_radar_linked and new.radar_candidate_id is distinct from old.radar_candidate_id then
    raise exception 'RADAR_DRAFT_ELIGIBILITY_LINK_IMMUTABLE' using errcode = '55000';
  end if;
  if old_radar_linked and new_link is distinct from old_link then
    initial_link := not (coalesce(old.source_provenance, '{}'::jsonb) ? 'radar_eligibility_check_id')
      and coalesce(new.source_provenance ->> 'radar_candidate_id', '') = new.radar_candidate_id::text
      and coalesce(new.source_provenance ->> 'radar_eligibility_check_id', '') ~ '^[1-9][0-9]*$'
      and new.source_provenance ->> 'radar_eligibility_policy_version' = 'atinara-prediction-policy-v5'
      and new.source_provenance ->> 'radar_eligibility_status' = 'eligible'
      and coalesce(new.source_provenance ->> 'radar_eligibility_decision_hash', '') ~ '^[0-9a-f]{64}$';
    safe_rebind := not initial_link
      and new.radar_candidate_id is not distinct from old.radar_candidate_id
      and new.content_version > old.content_version
      and new.review_status <> 'approved'
      and new.human_confirmed_at is null
      and new.scheduled_for is null
      and new.workflow_status in (
        'draft_incomplete', 'draft_ready', 'review_pending', 'review_in_progress',
        'review_rejected', 'review_inconclusive', 'review_unavailable'
      );
    if safe_rebind then
      -- Re-preparing a still-private draft is allowed only against the current
      -- authoritative revision/check and necessarily invalidates the old review.
      perform private.assert_market_radar_draft_eligibility_v1(new, clock_timestamp());
    elsif not initial_link then
      raise exception 'RADAR_DRAFT_ELIGIBILITY_LINK_IMMUTABLE' using errcode = '55000';
    end if;
  end if;
  if new.workflow_status in ('human_confirmed', 'scheduled', 'published') then
    perform private.assert_market_radar_draft_eligibility_v1(new, clock_timestamp());
  end if;
  return new;
end;
$function$;

revoke all on function private.market_draft_radar_eligibility_gate_v1()
  from public, anon, authenticated, service_role;

drop trigger if exists aaaa_market_draft_radar_eligibility_gate_v1
  on private.market_drafts;
create trigger aaaa_market_draft_radar_eligibility_gate_v1
before update of workflow_status, radar_candidate_id, source_provenance
on private.market_drafts
for each row execute function private.market_draft_radar_eligibility_gate_v1();

-- All Radar read APIs now expose the eligibility contract and deliberately
-- omit the retired factual dossier fields from operational payloads.
create or replace function private.market_radar_safe_payload(
  candidate private.external_market_candidates
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  select (
    candidate.normalized_payload
      - 'id' - 'preparation_revision'
      - 'current_fact_check_id' - 'fact_status' - 'fact_policy_version'
      - 'fact_context_fingerprint' - 'fact_checked_at'
      - 'fact_check_expires_at' - 'fact_check_purpose'
      - 'current_eligibility_check_id' - 'eligibility_status'
      - 'eligibility_reason_code' - 'eligibility_reason'
      - 'eligibility_evidence' - 'eligibility_checked_at'
      - 'eligibility_expires_at' - 'eligibility_policy_version'
  ) || jsonb_build_object(
    'id', candidate.id,
    'provider', candidate.provider,
    'external_id', candidate.external_id,
    'external_url', candidate.external_url,
    'external_event_id', candidate.external_event_id,
    'fingerprint', candidate.fingerprint,
    'cache_key', candidate.cache_key,
    'normalizer_version', candidate.normalizer_version,
    'source_status', candidate.source_status,
    'atinara_category', candidate.atinara_category,
    'source_excerpt', candidate.source_excerpt,
    'quality_status', candidate.quality_status,
    'quality_score', candidate.quality_score,
    'score_breakdown', candidate.score_breakdown,
    'warnings', candidate.warnings,
    'duplicate_matches', candidate.duplicate_matches,
    'hard_reject_reasons', private.market_candidate_authoritative_hard_reasons(
      candidate.normalized_payload, candidate.duplicate_matches
    ),
    'fetched_at', candidate.fetched_at,
    'source_updated_at', candidate.source_updated_at,
    'expires_at', candidate.expires_at,
    'cache_expires_at', candidate.expires_at,
    'is_stale', candidate.expires_at <= now(),
    'state', candidate.state,
    'prepared_draft_id', candidate.prepared_draft_id,
    'dismissed_at', candidate.dismissed_at,
    'dismissed_by', candidate.dismissed_by,
    'created_at', candidate.created_at,
    'updated_at', candidate.updated_at,
    'verification_status', candidate.verification_status,
    'verification_reason_code', candidate.verification_reason_code,
    'verification_reason', candidate.verification_reason,
    'verified_at', candidate.verified_at,
    'verification_expires_at', candidate.verification_expires_at,
    'verification_evidence', candidate.verification_evidence
  ) || jsonb_build_object(
    'event_group_key', candidate.event_group_key,
    'external_event_url', candidate.external_event_url,
    'external_market_url', candidate.external_market_url,
    'external_event_slug', candidate.external_event_slug,
    'external_market_slug', candidate.external_market_slug,
    'family_key', candidate.family_key,
    'family_title', candidate.family_title,
    'family_type', candidate.family_type,
    'family_child_key', candidate.family_child_key,
    'family_child_label', candidate.family_child_label,
    'family_sort_at', candidate.family_sort_at,
    'family_relationship', candidate.family_relationship,
    'family_semantics', candidate.family_semantics,
    'family_source_event_key', candidate.family_source_event_key,
    'family_version', candidate.family_version,
    'preparation_revision', candidate.preparation_revision,
    'eligibility_status', candidate.eligibility_status,
    'eligibility_reason_code', candidate.eligibility_reason_code,
    'eligibility_reason', candidate.eligibility_reason,
    'eligibility_evidence', candidate.eligibility_evidence,
    'eligibility_checked_at', candidate.eligibility_checked_at,
    'eligibility_expires_at', candidate.eligibility_expires_at,
    'eligibility_policy_version', candidate.eligibility_policy_version,
    'current_eligibility_check_id', candidate.current_eligibility_check_id
  );
$function$;

revoke all on function private.market_radar_safe_payload(
  private.external_market_candidates
) from public, anon, authenticated, service_role;

-- Eligibility checks are operational state. Refreshing the same decision must
-- not invalidate an Editor package or manufacture a material preparation
-- revision. Content changes such as a better resolution URL remain part of the
-- projection and therefore still increment the revision exactly once.
create or replace function private.market_candidate_preparation_projection(
  candidate private.external_market_candidates
)
returns jsonb
language sql
immutable
set search_path = ''
as $function$
  select (
    to_jsonb(candidate)
      - 'preparation_revision'
      - 'created_at'
      - 'updated_at'
      - 'cache_key'
      - 'fetched_at'
      - 'expires_at'
      - 'verification_status'
      - 'verification_reason_code'
      - 'verification_reason'
      - 'verification_evidence'
      - 'verification_confidence'
      - 'verified_at'
      - 'verification_expires_at'
      - 'fact_status'
      - 'fact_policy_version'
      - 'fact_context_fingerprint'
      - 'fact_checked_at'
      - 'fact_check_expires_at'
      - 'fact_check_purpose'
      - 'current_fact_check_id'
      - 'eligibility_status'
      - 'eligibility_reason_code'
      - 'eligibility_reason'
      - 'eligibility_evidence'
      - 'eligibility_checked_at'
      - 'eligibility_expires_at'
      - 'eligibility_policy_version'
      - 'current_eligibility_check_id'
  ) || jsonb_build_object(
    'normalized_payload', coalesce(candidate.normalized_payload, '{}'::jsonb)
      - 'id'
      - 'preparation_revision'
      - 'cache_key'
      - 'fetched_at'
      - 'cache_expires_at'
      - 'expires_at'
      - 'quality_status'
      - 'verification_status'
      - 'verification_reason_code'
      - 'verification_reason'
      - 'verification_evidence'
      - 'verification_confidence'
      - 'verified_at'
      - 'verification_expires_at'
      - 'fact_status'
      - 'fact_policy_version'
      - 'fact_context_fingerprint'
      - 'fact_checked_at'
      - 'fact_check_expires_at'
      - 'fact_check_purpose'
      - 'current_fact_check_id'
      - 'eligibility_status'
      - 'eligibility_reason_code'
      - 'eligibility_reason'
      - 'eligibility_evidence'
      - 'eligibility_checked_at'
      - 'eligibility_expires_at'
      - 'eligibility_policy_version'
      - 'current_eligibility_check_id'
  );
$function$;

revoke all on function private.market_candidate_preparation_projection(
  private.external_market_candidates
) from public, anon, authenticated, service_role;

-- The publication gate keeps all resolution-plan invariants, replacing only
-- the former requirement to prove an absence of news with a fresh, typed and
-- deterministic provider eligibility decision.
create or replace function private.assert_market_source_publication_ready(
  draft_id_input uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  draft_row private.market_drafts%rowtype;
  binding_row private.market_source_bindings%rowtype;
  provenance_state jsonb;
begin
  select * into draft_row
  from private.market_drafts
  where id = draft_id_input;
  if not found then raise exception 'DRAFT_NOT_FOUND' using errcode = 'P0001'; end if;

  perform private.assert_market_radar_draft_eligibility_v1(
    draft_row, clock_timestamp()
  );

  select * into binding_row
  from private.market_source_bindings
  where draft_id = draft_id_input
    and status <> 'superseded'
  order by plan_version desc, created_at desc
  limit 1;

  if draft_row.intelligence_origin_type is null and not found then return; end if;
  if not found then raise exception 'SOURCE_BINDING_REQUIRED' using errcode = '22023'; end if;
  if binding_row.contract_hash is null
     or binding_row.locked_at is null
     or binding_row.locked_by is null then
    raise exception 'RESOLUTION_PLAN_NOT_LOCKED' using errcode = '22023';
  end if;
  if binding_row.status not in ('validated', 'armed') then
    raise exception 'SOURCE_CONTRACT_NOT_LOCKED' using errcode = '22023';
  end if;
  if not coalesce((binding_row.validation ->> 'valid')::boolean, false) then
    raise exception 'SOURCE_BINDING_VALIDATION_REQUIRED'
      using errcode = '22023', detail = coalesce(binding_row.validation, '{}'::jsonb)::text;
  end if;
  if binding_row.contract_hash
     is distinct from private.market_intelligence_hash(binding_row.resolution_contract) then
    raise exception 'SOURCE_BINDING_CONTRACT_CHANGED' using errcode = '55000';
  end if;
  if binding_row.monitor_required
     and (binding_row.status <> 'armed' or binding_row.monitor_readiness <> 'armed') then
    raise exception 'SOURCE_MONITOR_NOT_ARMED' using errcode = '22023';
  end if;
  if binding_row.monitor_required and not coalesce((
    select enabled
    from private.market_intelligence_runtime_settings
    where setting_key = 'source_monitor_scheduler_enabled'
  ), false) then
    raise exception 'SOURCE_SCHEDULER_NOT_ENABLED' using errcode = '22023';
  end if;

  provenance_state := private.market_source_binding_provenance(binding_row.id);
  if not coalesce((provenance_state ->> 'valid')::boolean, false) then
    if provenance_state ->> 'mode' = 'completed_expert_run'
       and provenance_state -> 'issues' @> '["MARKET_EXPERT_ANALYSIS_REQUIRED"]'::jsonb then
      raise exception 'MARKET_EXPERT_ANALYSIS_REQUIRED'
        using errcode = '22023', detail = (provenance_state -> 'issues')::text;
    end if;
    raise exception 'SOURCE_BINDING_PROVENANCE_REQUIRED'
      using errcode = '22023', detail = (provenance_state -> 'issues')::text;
  end if;
end;
$function$;

revoke all on function private.assert_market_source_publication_ready(uuid)
  from public, anon, authenticated, service_role;

-- Retire the obsolete Editor incident rather than deleting its audit history.
update private.market_issue_strategy_registry
set active = false,
    updated_at = now()
where code = 'RADAR_FACTUAL_VERIFICATION_REQUIRED';

insert into private.market_issue_strategy_registry(
  code, phase, severity, disposition, strategy_key, affected_fields,
  invariants, evidence_required, expected_result, policy_version,
  schema_version, active, updated_at
) values
  (
    'RADAR_ELIGIBILITY_REQUIRED', 'editor', 'blocking', 'auto_recover',
    'refresh_deterministic_eligibility', '["eligibility_status"]'::jsonb,
    '["preserve_contract_meaning","preserve_private_state","never_confirm_or_publish"]'::jsonb,
    '["canonical_provider_state","exact_official_terminal_evidence"]'::jsonb,
    '{"draft_private":true,"requires_revalidation":true,"human_confirmation_required":true}'::jsonb,
    'atinara-expert-cycle-policy-v3', 'atinara-market-issue-contract-v1', true, now()
  ),
  (
    'RADAR_ELIGIBILITY_EXPIRED', 'publication', 'blocking', 'auto_recover',
    'refresh_deterministic_eligibility', '["eligibility_expires_at"]'::jsonb,
    '["preserve_contract_meaning","preserve_private_state","never_confirm_or_publish"]'::jsonb,
    '["canonical_provider_state","exact_official_terminal_evidence"]'::jsonb,
    '{"draft_private":true,"requires_revalidation":true,"human_confirmation_required":true}'::jsonb,
    'atinara-expert-cycle-policy-v3', 'atinara-market-issue-contract-v1', true, now()
  )
on conflict (code) do update set
  phase = excluded.phase,
  severity = excluded.severity,
  disposition = excluded.disposition,
  strategy_key = excluded.strategy_key,
  affected_fields = excluded.affected_fields,
  invariants = excluded.invariants,
  evidence_required = excluded.evidence_required,
  expected_result = excluded.expected_result,
  policy_version = excluded.policy_version,
  schema_version = excluded.schema_version,
  active = excluded.active,
  updated_at = excluded.updated_at;

comment on table private.market_radar_eligibility_checks is
  'Decisiones append-only de elegibilidad operativa; no son una revision factual ni una inferencia de ausencia de noticias.';
comment on function public.upsert_market_radar_batch_with_eligibility_v1(
  text,text,text,jsonb,jsonb,text,jsonb
) is 'Persiste candidatas y decisiones de elegibilidad por fila, con cuarentena aislada e idempotencia.';
comment on function public.apply_market_radar_prepare_eligibility_v1(
  uuid,bigint,text,timestamptz,jsonb,jsonb,boolean
) is 'Revalida proveedor y bloqueos terminales de forma atomica antes de preparar, confirmar o publicar.';

commit;
