-- AI Gateway V2.1: private runtime modes, atomic provider budgets and
-- payload-free append-only telemetry. No provider or routing flag is enabled.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table private.ai_task_runtime_settings (
  task_type text primary key,
  contract_version text not null,
  policy_version text not null,
  transport_mode text not null default 'legacy_direct',
  primary_route_id text,
  fallback_route_id text,
  openrouter_enabled boolean not null default false,
  nvidia_nim_enabled boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint ai_task_runtime_task_check check (task_type in (
    'radar_candidate_enrichment',
    'market_draft_validation',
    'market_expert_reasoning',
    'market_draft_repair',
    'market_resolution_analysis'
  )),
  constraint ai_task_runtime_mode_check check (transport_mode in (
    'legacy_direct', 'gateway_gemini_parity', 'gateway_routing'
  )),
  constraint ai_task_runtime_route_check check (
    transport_mode <> 'gateway_routing' or primary_route_id is not null
  ),
  constraint ai_task_runtime_experimental_check check (
    transport_mode = 'gateway_routing' or (not openrouter_enabled and not nvidia_nim_enabled)
  )
);

create table private.ai_provider_budget_limits (
  provider_id text not null,
  task_type text not null,
  daily_limit_units bigint not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (provider_id, task_type),
  constraint ai_provider_budget_limits_provider_check check (provider_id in ('gemini', 'openrouter', 'nvidia_nim')),
  constraint ai_provider_budget_limits_task_check check (task_type in (
    'radar_candidate_enrichment',
    'market_draft_validation',
    'market_expert_reasoning',
    'market_draft_repair',
    'market_resolution_analysis'
  )),
  constraint ai_provider_budget_limits_nonnegative_check check (daily_limit_units >= 0)
);

create table private.ai_provider_budget_days (
  provider_id text not null,
  task_type text not null,
  budget_day date not null,
  limit_units bigint not null,
  used_units bigint not null default 0,
  created_at timestamptz not null default now(),
  primary key (provider_id, task_type, budget_day),
  constraint ai_provider_budget_days_nonnegative_check check (
    limit_units >= 0 and used_units >= 0 and used_units <= limit_units
  )
);

create table private.ai_provider_budget_reservations (
  invocation_id text not null,
  provider_id text not null,
  task_type text not null,
  budget_day date not null,
  requested_units bigint not null,
  budget_mode text not null,
  status text not null,
  used_units bigint,
  limit_units bigint,
  created_at timestamptz not null default now(),
  primary key (invocation_id, provider_id, task_type, budget_day),
  constraint ai_budget_reservation_invocation_check check (
    char_length(invocation_id) between 1 and 120 and invocation_id ~ '^[A-Za-z0-9._:-]+$'
  ),
  constraint ai_budget_reservation_requested_check check (requested_units > 0),
  constraint ai_budget_reservation_mode_check check (budget_mode in ('baseline_existing', 'metered')),
  constraint ai_budget_reservation_status_check check (status in ('reserved', 'exhausted')),
  constraint ai_budget_reservation_result_check check (
    (status = 'reserved' and (budget_mode = 'baseline_existing' or used_units is not null))
    or (status = 'exhausted' and used_units is not null and limit_units is not null)
  )
);

create index ai_provider_budget_reservations_created_idx
  on private.ai_provider_budget_reservations(created_at);

create table private.ai_invocation_attempts (
  id bigint generated by default as identity primary key,
  invocation_id text not null,
  agent_run_id text,
  task_type text not null,
  contract_version text not null,
  policy_version text not null,
  transport_mode text not null,
  route_id text not null,
  provider_id text not null,
  model_id text,
  data_class text not null,
  input_fingerprint text not null,
  output_fingerprint text,
  lifecycle jsonb not null default '[]'::jsonb,
  outcome text not null,
  error_code text,
  retry_count integer not null default 0,
  response_bytes integer not null default 0,
  duration_ms integer not null default 0,
  input_tokens integer,
  output_tokens integer,
  provider_request_id text,
  schema_fallback boolean not null default false,
  metrics_eligible boolean not null default false,
  created_at timestamptz not null default now(),
  unique (invocation_id, route_id),
  constraint ai_invocation_attempt_id_check check (
    char_length(invocation_id) between 1 and 120 and invocation_id ~ '^[A-Za-z0-9._:-]+$'
  ),
  constraint ai_invocation_attempt_agent_check check (
    agent_run_id is null or (char_length(agent_run_id) between 1 and 120 and agent_run_id ~ '^[A-Za-z0-9._:-]+$')
  ),
  constraint ai_invocation_attempt_mode_check check (transport_mode in (
    'legacy_direct', 'gateway_gemini_parity', 'gateway_routing'
  )),
  constraint ai_invocation_attempt_provider_check check (provider_id in ('gemini', 'openrouter', 'nvidia_nim')),
  constraint ai_invocation_attempt_data_class_check check (data_class in (
    'public_market', 'private_market_minimized', 'prohibited'
  )),
  constraint ai_invocation_attempt_input_hash_check check (input_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint ai_invocation_attempt_output_hash_check check (
    output_fingerprint is null or output_fingerprint ~ '^[0-9a-f]{64}$'
  ),
  constraint ai_invocation_attempt_lifecycle_check check (
    jsonb_typeof(lifecycle) = 'array' and jsonb_array_length(lifecycle) <= 20
  ),
  constraint ai_invocation_attempt_outcome_check check (outcome in ('accepted', 'technical_failure')),
  constraint ai_invocation_attempt_error_check check (
    (outcome = 'accepted' and error_code is null and output_fingerprint is not null)
    or (outcome = 'technical_failure' and error_code ~ '^AI_[A-Z0-9_]{2,100}$')
  ),
  constraint ai_invocation_attempt_numbers_check check (
    retry_count >= 0 and response_bytes >= 0 and duration_ms >= 0
    and (input_tokens is null or input_tokens >= 0)
    and (output_tokens is null or output_tokens >= 0)
  )
);

create index ai_invocation_attempts_created_idx on private.ai_invocation_attempts(created_at);
create index ai_invocation_attempts_task_created_idx on private.ai_invocation_attempts(task_type, created_at desc);

create table private.ai_retention_audit (
  id bigint generated by default as identity primary key,
  detailed_cutoff timestamptz not null,
  operational_cutoff timestamptz not null,
  invocation_rows_deleted bigint not null default 0,
  run_rows_deleted bigint not null default 0,
  step_rows_deleted bigint not null default 0,
  executed_at timestamptz not null default now(),
  constraint ai_retention_audit_counts_check check (
    invocation_rows_deleted >= 0 and run_rows_deleted >= 0 and step_rows_deleted >= 0
  )
);

alter table private.ai_task_runtime_settings enable row level security;
alter table private.ai_task_runtime_settings force row level security;
alter table private.ai_provider_budget_limits enable row level security;
alter table private.ai_provider_budget_limits force row level security;
alter table private.ai_provider_budget_days enable row level security;
alter table private.ai_provider_budget_days force row level security;
alter table private.ai_provider_budget_reservations enable row level security;
alter table private.ai_provider_budget_reservations force row level security;
alter table private.ai_invocation_attempts enable row level security;
alter table private.ai_invocation_attempts force row level security;
alter table private.ai_retention_audit enable row level security;
alter table private.ai_retention_audit force row level security;

revoke all on table private.ai_task_runtime_settings from public, anon, authenticated, service_role;
revoke all on table private.ai_provider_budget_limits from public, anon, authenticated, service_role;
revoke all on table private.ai_provider_budget_days from public, anon, authenticated, service_role;
revoke all on table private.ai_provider_budget_reservations from public, anon, authenticated, service_role;
revoke all on table private.ai_invocation_attempts from public, anon, authenticated, service_role;
revoke all on sequence private.ai_invocation_attempts_id_seq from public, anon, authenticated, service_role;
revoke all on table private.ai_retention_audit from public, anon, authenticated, service_role;
revoke all on sequence private.ai_retention_audit_id_seq from public, anon, authenticated, service_role;

create or replace function private.reject_ai_append_only_update_v1()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  raise exception 'AI_APPEND_ONLY_UPDATE_PROHIBITED' using errcode = '55000';
end;
$function$;

revoke all on function private.reject_ai_append_only_update_v1()
  from public, anon, authenticated, service_role;

create trigger reject_ai_budget_reservation_update_v1
before update on private.ai_provider_budget_reservations
for each row execute function private.reject_ai_append_only_update_v1();

create trigger reject_ai_invocation_attempt_update_v1
before update on private.ai_invocation_attempts
for each row execute function private.reject_ai_append_only_update_v1();

create trigger reject_ai_retention_audit_update_v1
before update on private.ai_retention_audit
for each row execute function private.reject_ai_append_only_update_v1();

insert into private.ai_task_runtime_settings (
  task_type, contract_version, policy_version, transport_mode,
  primary_route_id, fallback_route_id, openrouter_enabled, nvidia_nim_enabled
)
values
  ('radar_candidate_enrichment', 'atinara-ai-radar-candidate-enrichment-v1', 'atinara-prediction-policy-v5', 'legacy_direct', null, null, false, false),
  ('market_draft_validation', 'atinara-ai-market-draft-validation-v1', 'atinara-market-review-policy-v3', 'legacy_direct', null, null, false, false),
  ('market_expert_reasoning', 'atinara-ai-market-expert-reasoning-v1', 'atinara-market-constitution-v1', 'legacy_direct', null, null, false, false),
  ('market_draft_repair', 'atinara-ai-market-draft-repair-v1', 'atinara-draft-repair-v12', 'legacy_direct', null, null, false, false),
  ('market_resolution_analysis', 'atinara-ai-market-resolution-analysis-v1', 'atinara-resolution-analysis-policy-v1', 'legacy_direct', null, null, false, false);

insert into private.ai_provider_budget_limits (provider_id, task_type, daily_limit_units)
select provider_id, task_type, 0
from unnest(array['gemini', 'openrouter', 'nvidia_nim']) as provider_rows(provider_id)
cross join unnest(array[
  'radar_candidate_enrichment',
  'market_draft_validation',
  'market_expert_reasoning',
  'market_draft_repair',
  'market_resolution_analysis'
]) as task_rows(task_type);

create or replace function private.get_ai_task_runtime_mode_private_v1(task_type_input text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $function$
  select jsonb_build_object(
    'task_type', setting.task_type,
    'contract_version', setting.contract_version,
    'policy_version', setting.policy_version,
    'transport_mode', setting.transport_mode,
    'primary_route_id', setting.primary_route_id,
    'fallback_route_id', setting.fallback_route_id,
    'openrouter_enabled', setting.openrouter_enabled,
    'nvidia_nim_enabled', setting.nvidia_nim_enabled
  )
  from private.ai_task_runtime_settings setting
  where setting.task_type = trim(task_type_input);
$function$;

revoke all on function private.get_ai_task_runtime_mode_private_v1(text)
  from public, anon, authenticated, service_role;

create or replace function public.get_ai_task_runtime_mode_v1(task_type_input text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
begin
  if private.market_request_role_v1() is distinct from 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  return private.get_ai_task_runtime_mode_private_v1(task_type_input);
end;
$function$;

revoke all on function public.get_ai_task_runtime_mode_v1(text)
  from public, anon, authenticated, service_role;
grant execute on function public.get_ai_task_runtime_mode_v1(text) to service_role;

create or replace function private.reserve_ai_provider_budget_private_v1(
  invocation_id_input text,
  provider_id_input text,
  task_type_input text,
  requested_units_input bigint,
  budget_mode_input text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
declare
  invocation_value text := trim(coalesce(invocation_id_input, ''));
  provider_value text := trim(coalesce(provider_id_input, ''));
  task_value text := trim(coalesce(task_type_input, ''));
  mode_value text := trim(coalesce(budget_mode_input, ''));
  day_value date := (clock_timestamp() at time zone 'UTC')::date;
  previous private.ai_provider_budget_reservations%rowtype;
  limit_value bigint;
  used_value bigint;
  status_value text;
begin
  if invocation_value !~ '^[A-Za-z0-9._:-]{1,120}$'
     or provider_value not in ('gemini', 'openrouter', 'nvidia_nim')
     or task_value not in (
       'radar_candidate_enrichment', 'market_draft_validation', 'market_expert_reasoning',
       'market_draft_repair', 'market_resolution_analysis'
     )
     or requested_units_input is null or requested_units_input < 1
     or mode_value not in ('baseline_existing', 'metered') then
    raise exception 'AI_BUDGET_INVALID_REQUEST' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(provider_value || ':' || task_value || ':' || day_value::text, 0)
  );

  select * into previous
  from private.ai_provider_budget_reservations reservation
  where reservation.invocation_id = invocation_value
    and reservation.provider_id = provider_value
    and reservation.task_type = task_value
    and reservation.budget_day = day_value;

  if found then
    if previous.requested_units <> requested_units_input or previous.budget_mode <> mode_value then
      raise exception 'AI_BUDGET_IDEMPOTENCY_CONFLICT' using errcode = '23505';
    end if;
    return jsonb_build_object(
      'status', previous.status,
      'reserved', previous.status = 'reserved',
      'idempotent', true,
      'requested_units', previous.requested_units,
      'used_units', previous.used_units,
      'limit_units', previous.limit_units
    );
  end if;

  if mode_value = 'baseline_existing' then
    insert into private.ai_provider_budget_reservations (
      invocation_id, provider_id, task_type, budget_day, requested_units,
      budget_mode, status, used_units, limit_units
    ) values (
      invocation_value, provider_value, task_value, day_value, requested_units_input,
      mode_value, 'reserved', null, null
    );
    return jsonb_build_object(
      'status', 'reserved', 'reserved', true, 'idempotent', false,
      'requested_units', requested_units_input, 'used_units', null, 'limit_units', null
    );
  end if;

  select coalesce(limit_row.daily_limit_units, 0)
    into limit_value
  from private.ai_provider_budget_limits limit_row
  where limit_row.provider_id = provider_value
    and limit_row.task_type = task_value
    and limit_row.active
  for share;
  limit_value := coalesce(limit_value, 0);

  insert into private.ai_provider_budget_days (
    provider_id, task_type, budget_day, limit_units, used_units
  ) values (
    provider_value, task_value, day_value, limit_value, 0
  ) on conflict (provider_id, task_type, budget_day) do nothing;

  update private.ai_provider_budget_days budget_day
  set used_units = budget_day.used_units + requested_units_input
  where budget_day.provider_id = provider_value
    and budget_day.task_type = task_value
    and budget_day.budget_day = day_value
    and budget_day.used_units + requested_units_input <= budget_day.limit_units
  returning budget_day.used_units, budget_day.limit_units into used_value, limit_value;

  if found then
    status_value := 'reserved';
  else
    status_value := 'exhausted';
    select budget_day.used_units, budget_day.limit_units
      into used_value, limit_value
    from private.ai_provider_budget_days budget_day
    where budget_day.provider_id = provider_value
      and budget_day.task_type = task_value
      and budget_day.budget_day = day_value;
  end if;

  insert into private.ai_provider_budget_reservations (
    invocation_id, provider_id, task_type, budget_day, requested_units,
    budget_mode, status, used_units, limit_units
  ) values (
    invocation_value, provider_value, task_value, day_value, requested_units_input,
    mode_value, status_value, used_value, limit_value
  );

  return jsonb_build_object(
    'status', status_value,
    'reserved', status_value = 'reserved',
    'idempotent', false,
    'requested_units', requested_units_input,
    'used_units', used_value,
    'limit_units', limit_value
  );
end;
$function$;

revoke all on function private.reserve_ai_provider_budget_private_v1(text,text,text,bigint,text)
  from public, anon, authenticated, service_role;

create or replace function public.reserve_ai_provider_budget_v1(
  invocation_id_input text,
  provider_id_input text,
  task_type_input text,
  requested_units_input bigint,
  budget_mode_input text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
begin
  if private.market_request_role_v1() is distinct from 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  return private.reserve_ai_provider_budget_private_v1(
    invocation_id_input, provider_id_input, task_type_input,
    requested_units_input, budget_mode_input
  );
end;
$function$;

revoke all on function public.reserve_ai_provider_budget_v1(text,text,text,bigint,text)
  from public, anon, authenticated, service_role;
grant execute on function public.reserve_ai_provider_budget_v1(text,text,text,bigint,text)
  to service_role;

create or replace function private.record_ai_invocation_attempt_private_v1(payload_input jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
declare
  existing private.ai_invocation_attempts%rowtype;
  inserted_id bigint;
  invocation_value text := trim(coalesce(payload_input ->> 'invocation_id', ''));
  route_value text := trim(coalesce(payload_input ->> 'route_id', ''));
begin
  if jsonb_typeof(payload_input) <> 'object'
     or invocation_value !~ '^[A-Za-z0-9._:-]{1,120}$'
     or route_value = '' then
    raise exception 'AI_TELEMETRY_INVALID_REQUEST' using errcode = '22023';
  end if;

  select * into existing
  from private.ai_invocation_attempts attempt
  where attempt.invocation_id = invocation_value and attempt.route_id = route_value;
  if found then
    if existing.input_fingerprint <> payload_input ->> 'input_fingerprint'
       or existing.output_fingerprint is distinct from nullif(payload_input ->> 'output_fingerprint', '')
       or existing.outcome <> payload_input ->> 'outcome' then
      raise exception 'AI_TELEMETRY_IDEMPOTENCY_CONFLICT' using errcode = '23505';
    end if;
    return jsonb_build_object('id', existing.id, 'idempotent', true);
  end if;

  insert into private.ai_invocation_attempts (
    invocation_id, agent_run_id, task_type, contract_version, policy_version,
    transport_mode, route_id, provider_id, model_id, data_class,
    input_fingerprint, output_fingerprint, lifecycle, outcome, error_code,
    retry_count, response_bytes, duration_ms, input_tokens, output_tokens,
    provider_request_id, schema_fallback, metrics_eligible
  ) values (
    invocation_value,
    nullif(payload_input ->> 'agent_run_id', ''),
    payload_input ->> 'task_type',
    payload_input ->> 'contract_version',
    payload_input ->> 'policy_version',
    payload_input ->> 'transport_mode',
    route_value,
    payload_input ->> 'provider_id',
    nullif(payload_input ->> 'model_id', ''),
    payload_input ->> 'data_class',
    payload_input ->> 'input_fingerprint',
    nullif(payload_input ->> 'output_fingerprint', ''),
    coalesce(payload_input -> 'lifecycle', '[]'::jsonb),
    payload_input ->> 'outcome',
    nullif(payload_input ->> 'error_code', ''),
    coalesce((payload_input ->> 'retry_count')::integer, 0),
    coalesce((payload_input ->> 'response_bytes')::integer, 0),
    coalesce((payload_input ->> 'duration_ms')::integer, 0),
    (payload_input ->> 'input_tokens')::integer,
    (payload_input ->> 'output_tokens')::integer,
    nullif(left(payload_input ->> 'provider_request_id', 160), ''),
    coalesce((payload_input ->> 'schema_fallback')::boolean, false),
    coalesce((payload_input ->> 'metrics_eligible')::boolean, false)
  ) returning id into inserted_id;
  return jsonb_build_object('id', inserted_id, 'idempotent', false);
end;
$function$;

revoke all on function private.record_ai_invocation_attempt_private_v1(jsonb)
  from public, anon, authenticated, service_role;

create or replace function public.record_ai_invocation_attempt_v1(
  invocation_id_input text,
  agent_run_id_input text,
  task_type_input text,
  contract_version_input text,
  policy_version_input text,
  transport_mode_input text,
  route_id_input text,
  provider_id_input text,
  model_id_input text,
  data_class_input text,
  input_fingerprint_input text,
  output_fingerprint_input text,
  lifecycle_input jsonb,
  outcome_input text,
  error_code_input text,
  retry_count_input integer,
  response_bytes_input integer,
  duration_ms_input integer,
  input_tokens_input integer,
  output_tokens_input integer,
  provider_request_id_input text,
  schema_fallback_input boolean,
  metrics_eligible_input boolean
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
begin
  if private.market_request_role_v1() is distinct from 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  return private.record_ai_invocation_attempt_private_v1(jsonb_build_object(
    'invocation_id', invocation_id_input,
    'agent_run_id', agent_run_id_input,
    'task_type', task_type_input,
    'contract_version', contract_version_input,
    'policy_version', policy_version_input,
    'transport_mode', transport_mode_input,
    'route_id', route_id_input,
    'provider_id', provider_id_input,
    'model_id', model_id_input,
    'data_class', data_class_input,
    'input_fingerprint', input_fingerprint_input,
    'output_fingerprint', output_fingerprint_input,
    'lifecycle', lifecycle_input,
    'outcome', outcome_input,
    'error_code', error_code_input,
    'retry_count', retry_count_input,
    'response_bytes', response_bytes_input,
    'duration_ms', duration_ms_input,
    'input_tokens', input_tokens_input,
    'output_tokens', output_tokens_input,
    'provider_request_id', provider_request_id_input,
    'schema_fallback', schema_fallback_input,
    'metrics_eligible', metrics_eligible_input
  ));
end;
$function$;

revoke all on function public.record_ai_invocation_attempt_v1(
  text,text,text,text,text,text,text,text,text,text,text,text,jsonb,text,text,
  integer,integer,integer,integer,integer,text,boolean,boolean
) from public, anon, authenticated, service_role;
grant execute on function public.record_ai_invocation_attempt_v1(
  text,text,text,text,text,text,text,text,text,text,text,text,jsonb,text,text,
  integer,integer,integer,integer,integer,text,boolean,boolean
) to service_role;

create or replace function private.purge_ai_operational_telemetry_private_v1()
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
declare
  detailed_cutoff_value timestamptz := clock_timestamp() - interval '90 days';
  operational_cutoff_value timestamptz := clock_timestamp() - interval '180 days';
  invocation_count bigint := 0;
begin
  delete from private.ai_invocation_attempts
  where created_at < detailed_cutoff_value;
  get diagnostics invocation_count = row_count;

  insert into private.ai_retention_audit (
    detailed_cutoff, operational_cutoff, invocation_rows_deleted,
    run_rows_deleted, step_rows_deleted
  ) values (
    detailed_cutoff_value, operational_cutoff_value, invocation_count, 0, 0
  );
  return jsonb_build_object(
    'detailed_cutoff', detailed_cutoff_value,
    'operational_cutoff', operational_cutoff_value,
    'invocation_rows_deleted', invocation_count,
    'run_rows_deleted', 0,
    'step_rows_deleted', 0
  );
end;
$function$;

revoke all on function private.purge_ai_operational_telemetry_private_v1()
  from public, anon, authenticated, service_role;

create or replace function public.purge_ai_operational_telemetry_v1()
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $function$
begin
  if private.market_request_role_v1() is distinct from 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  return private.purge_ai_operational_telemetry_private_v1();
end;
$function$;

revoke all on function public.purge_ai_operational_telemetry_v1()
  from public, anon, authenticated, service_role;
grant execute on function public.purge_ai_operational_telemetry_v1()
  to service_role;

comment on table private.ai_task_runtime_settings is
  'Transición por tarea: legacy_direct, gateway_gemini_parity o gateway_routing. Los proveedores experimentales nacen apagados.';
comment on table private.ai_provider_budget_reservations is
  'Reservas atómicas e idempotentes por invocation, proveedor, tarea y día UTC.';
comment on table private.ai_invocation_attempts is
  'Telemetría append-only sin prompts, payloads, respuestas ni secretos; detalle retenido 90 días.';
comment on function public.purge_ai_operational_telemetry_v1() is
  'Purga service-only con cutoffs internos fijos; no acepta IDs ni fechas del caller.';

commit;
